// XS Wallet - Common Types
// Tipos compartilhados entre todos os serviços

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: common.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Chain int32

const (
	Chain_CHAIN_UNSPECIFIED Chain = 0
	Chain_CHAIN_BTC         Chain = 1
	Chain_CHAIN_LIQUID      Chain = 2
	Chain_CHAIN_LN          Chain = 3
)

// Enum value maps for Chain.
var (
	Chain_name = map[int32]string{
		0: "CHAIN_UNSPECIFIED",
		1: "CHAIN_BTC",
		2: "CHAIN_LIQUID",
		3: "CHAIN_LN",
	}
	Chain_value = map[string]int32{
		"CHAIN_UNSPECIFIED": 0,
		"CHAIN_BTC":         1,
		"CHAIN_LIQUID":      2,
		"CHAIN_LN":          3,
	}
)

func (x Chain) Enum() *Chain {
	p := new(Chain)
	*p = x
	return p
}

func (x Chain) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Chain) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (Chain) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x Chain) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Chain.Descriptor instead.
func (Chain) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

type Network int32

const (
	Network_NETWORK_UNSPECIFIED Network = 0
	Network_NETWORK_MAINNET     Network = 1
	Network_NETWORK_TESTNET     Network = 2
	Network_NETWORK_REGTEST     Network = 3
)

// Enum value maps for Network.
var (
	Network_name = map[int32]string{
		0: "NETWORK_UNSPECIFIED",
		1: "NETWORK_MAINNET",
		2: "NETWORK_TESTNET",
		3: "NETWORK_REGTEST",
	}
	Network_value = map[string]int32{
		"NETWORK_UNSPECIFIED": 0,
		"NETWORK_MAINNET":     1,
		"NETWORK_TESTNET":     2,
		"NETWORK_REGTEST":     3,
	}
)

func (x Network) Enum() *Network {
	p := new(Network)
	*p = x
	return p
}

func (x Network) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Network) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[1].Descriptor()
}

func (Network) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[1]
}

func (x Network) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Network.Descriptor instead.
func (Network) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

type FeePolicy_Priority int32

const (
	FeePolicy_PRIORITY_UNSPECIFIED FeePolicy_Priority = 0
	FeePolicy_PRIORITY_LOW         FeePolicy_Priority = 1 // ~6 blocos
	FeePolicy_PRIORITY_MEDIUM      FeePolicy_Priority = 2 // ~3 blocos
	FeePolicy_PRIORITY_HIGH        FeePolicy_Priority = 3 // próximo bloco
)

// Enum value maps for FeePolicy_Priority.
var (
	FeePolicy_Priority_name = map[int32]string{
		0: "PRIORITY_UNSPECIFIED",
		1: "PRIORITY_LOW",
		2: "PRIORITY_MEDIUM",
		3: "PRIORITY_HIGH",
	}
	FeePolicy_Priority_value = map[string]int32{
		"PRIORITY_UNSPECIFIED": 0,
		"PRIORITY_LOW":         1,
		"PRIORITY_MEDIUM":      2,
		"PRIORITY_HIGH":        3,
	}
)

func (x FeePolicy_Priority) Enum() *FeePolicy_Priority {
	p := new(FeePolicy_Priority)
	*p = x
	return p
}

func (x FeePolicy_Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FeePolicy_Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[2].Descriptor()
}

func (FeePolicy_Priority) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[2]
}

func (x FeePolicy_Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FeePolicy_Priority.Descriptor instead.
func (FeePolicy_Priority) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0, 0}
}

type FeePolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Priority      FeePolicy_Priority     `protobuf:"varint,1,opt,name=priority,proto3,enum=xswallet.FeePolicy_Priority" json:"priority,omitempty"`
	MaxFeeSat     uint64                 `protobuf:"varint,2,opt,name=max_fee_sat,json=maxFeeSat,proto3" json:"max_fee_sat,omitempty"` // Limite máximo de fee
	AllowRbf      bool                   `protobuf:"varint,3,opt,name=allow_rbf,json=allowRbf,proto3" json:"allow_rbf,omitempty"`      // Permitir RBF
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeePolicy) Reset() {
	*x = FeePolicy{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeePolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeePolicy) ProtoMessage() {}

func (x *FeePolicy) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeePolicy.ProtoReflect.Descriptor instead.
func (*FeePolicy) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *FeePolicy) GetPriority() FeePolicy_Priority {
	if x != nil {
		return x.Priority
	}
	return FeePolicy_PRIORITY_UNSPECIFIED
}

func (x *FeePolicy) GetMaxFeeSat() uint64 {
	if x != nil {
		return x.MaxFeeSat
	}
	return 0
}

func (x *FeePolicy) GetAllowRbf() bool {
	if x != nil {
		return x.AllowRbf
	}
	return false
}

type PlatformCapabilities struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CanSpawnNodes       bool                   `protobuf:"varint,1,opt,name=can_spawn_nodes,json=canSpawnNodes,proto3" json:"can_spawn_nodes,omitempty"`                   // Desktop: true, Mobile: false
	CanDownloadBinaries bool                   `protobuf:"varint,2,opt,name=can_download_binaries,json=canDownloadBinaries,proto3" json:"can_download_binaries,omitempty"` // Desktop: true, Mobile: false
	HasEmbeddedNeutrino bool                   `protobuf:"varint,3,opt,name=has_embedded_neutrino,json=hasEmbeddedNeutrino,proto3" json:"has_embedded_neutrino,omitempty"` // Mobile: true, Desktop: false
	Platform            string                 `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`                                                     // "desktop", "ios", "android"
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PlatformCapabilities) Reset() {
	*x = PlatformCapabilities{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformCapabilities) ProtoMessage() {}

func (x *PlatformCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatformCapabilities.ProtoReflect.Descriptor instead.
func (*PlatformCapabilities) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *PlatformCapabilities) GetCanSpawnNodes() bool {
	if x != nil {
		return x.CanSpawnNodes
	}
	return false
}

func (x *PlatformCapabilities) GetCanDownloadBinaries() bool {
	if x != nil {
		return x.CanDownloadBinaries
	}
	return false
}

func (x *PlatformCapabilities) GetHasEmbeddedNeutrino() bool {
	if x != nil {
		return x.HasEmbeddedNeutrino
	}
	return false
}

func (x *PlatformCapabilities) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\bxswallet\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe2\x01\n" +
	"\tFeePolicy\x128\n" +
	"\bpriority\x18\x01 \x01(\x0e2\x1c.xswallet.FeePolicy.PriorityR\bpriority\x12\x1e\n" +
	"\vmax_fee_sat\x18\x02 \x01(\x04R\tmaxFeeSat\x12\x1b\n" +
	"\tallow_rbf\x18\x03 \x01(\bR\ballowRbf\"^\n" +
	"\bPriority\x12\x18\n" +
	"\x14PRIORITY_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fPRIORITY_LOW\x10\x01\x12\x13\n" +
	"\x0fPRIORITY_MEDIUM\x10\x02\x12\x11\n" +
	"\rPRIORITY_HIGH\x10\x03\"\xc2\x01\n" +
	"\x14PlatformCapabilities\x12&\n" +
	"\x0fcan_spawn_nodes\x18\x01 \x01(\bR\rcanSpawnNodes\x122\n" +
	"\x15can_download_binaries\x18\x02 \x01(\bR\x13canDownloadBinaries\x122\n" +
	"\x15has_embedded_neutrino\x18\x03 \x01(\bR\x13hasEmbeddedNeutrino\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform*M\n" +
	"\x05Chain\x12\x15\n" +
	"\x11CHAIN_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tCHAIN_BTC\x10\x01\x12\x10\n" +
	"\fCHAIN_LIQUID\x10\x02\x12\f\n" +
	"\bCHAIN_LN\x10\x03*a\n" +
	"\aNetwork\x12\x17\n" +
	"\x13NETWORK_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fNETWORK_MAINNET\x10\x01\x12\x13\n" +
	"\x0fNETWORK_TESTNET\x10\x02\x12\x13\n" +
	"\x0fNETWORK_REGTEST\x10\x03B#Z!github.com/xs-wallet/xscore/protob\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_proto_goTypes = []any{
	(Chain)(0),                   // 0: xswallet.Chain
	(Network)(0),                 // 1: xswallet.Network
	(FeePolicy_Priority)(0),      // 2: xswallet.FeePolicy.Priority
	(*FeePolicy)(nil),            // 3: xswallet.FeePolicy
	(*PlatformCapabilities)(nil), // 4: xswallet.PlatformCapabilities
}
var file_common_proto_depIdxs = []int32{
	2, // 0: xswallet.FeePolicy.priority:type_name -> xswallet.FeePolicy.Priority
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
