// XS Wallet - Node Service Protocol
// Gerenciamento de nodes embarcados (bitcoind, elementsd, LND)

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: node.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeType int32

const (
	NodeType_NODE_TYPE_UNSPECIFIED NodeType = 0
	NodeType_NODE_TYPE_BITCOIND    NodeType = 1
	NodeType_NODE_TYPE_ELEMENTSD   NodeType = 2
	NodeType_NODE_TYPE_LND         NodeType = 3
)

// Enum value maps for NodeType.
var (
	NodeType_name = map[int32]string{
		0: "NODE_TYPE_UNSPECIFIED",
		1: "NODE_TYPE_BITCOIND",
		2: "NODE_TYPE_ELEMENTSD",
		3: "NODE_TYPE_LND",
	}
	NodeType_value = map[string]int32{
		"NODE_TYPE_UNSPECIFIED": 0,
		"NODE_TYPE_BITCOIND":    1,
		"NODE_TYPE_ELEMENTSD":   2,
		"NODE_TYPE_LND":         3,
	}
)

func (x NodeType) Enum() *NodeType {
	p := new(NodeType)
	*p = x
	return p
}

func (x NodeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeType) Descriptor() protoreflect.EnumDescriptor {
	return file_node_proto_enumTypes[0].Descriptor()
}

func (NodeType) Type() protoreflect.EnumType {
	return &file_node_proto_enumTypes[0]
}

func (x NodeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeType.Descriptor instead.
func (NodeType) EnumDescriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{0}
}

type NodeState int32

const (
	NodeState_NODE_STATE_UNSPECIFIED   NodeState = 0
	NodeState_NODE_STATE_NOT_INSTALLED NodeState = 1 // Binário não existe (desktop)
	NodeState_NODE_STATE_STOPPED       NodeState = 2 // Instalado mas não rodando
	NodeState_NODE_STATE_STARTING      NodeState = 3 // Iniciando
	NodeState_NODE_STATE_SYNCING       NodeState = 4 // Rodando, sincronizando
	NodeState_NODE_STATE_RUNNING       NodeState = 5 // Rodando, sincronizado
	NodeState_NODE_STATE_STOPPING      NodeState = 6 // Parando
	NodeState_NODE_STATE_ERROR         NodeState = 7 // Erro
)

// Enum value maps for NodeState.
var (
	NodeState_name = map[int32]string{
		0: "NODE_STATE_UNSPECIFIED",
		1: "NODE_STATE_NOT_INSTALLED",
		2: "NODE_STATE_STOPPED",
		3: "NODE_STATE_STARTING",
		4: "NODE_STATE_SYNCING",
		5: "NODE_STATE_RUNNING",
		6: "NODE_STATE_STOPPING",
		7: "NODE_STATE_ERROR",
	}
	NodeState_value = map[string]int32{
		"NODE_STATE_UNSPECIFIED":   0,
		"NODE_STATE_NOT_INSTALLED": 1,
		"NODE_STATE_STOPPED":       2,
		"NODE_STATE_STARTING":      3,
		"NODE_STATE_SYNCING":       4,
		"NODE_STATE_RUNNING":       5,
		"NODE_STATE_STOPPING":      6,
		"NODE_STATE_ERROR":         7,
	}
)

func (x NodeState) Enum() *NodeState {
	p := new(NodeState)
	*p = x
	return p
}

func (x NodeState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeState) Descriptor() protoreflect.EnumDescriptor {
	return file_node_proto_enumTypes[1].Descriptor()
}

func (NodeState) Type() protoreflect.EnumType {
	return &file_node_proto_enumTypes[1]
}

func (x NodeState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeState.Descriptor instead.
func (NodeState) EnumDescriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{1}
}

type GetPlatformCapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlatformCapabilitiesRequest) Reset() {
	*x = GetPlatformCapabilitiesRequest{}
	mi := &file_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlatformCapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlatformCapabilitiesRequest) ProtoMessage() {}

func (x *GetPlatformCapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlatformCapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*GetPlatformCapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{0}
}

type StartNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeType      NodeType               `protobuf:"varint,1,opt,name=node_type,json=nodeType,proto3,enum=xswallet.NodeType" json:"node_type,omitempty"`
	Network       Network                `protobuf:"varint,2,opt,name=network,proto3,enum=xswallet.Network" json:"network,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartNodeRequest) Reset() {
	*x = StartNodeRequest{}
	mi := &file_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartNodeRequest) ProtoMessage() {}

func (x *StartNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartNodeRequest.ProtoReflect.Descriptor instead.
func (*StartNodeRequest) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{1}
}

func (x *StartNodeRequest) GetNodeType() NodeType {
	if x != nil {
		return x.NodeType
	}
	return NodeType_NODE_TYPE_UNSPECIFIED
}

func (x *StartNodeRequest) GetNetwork() Network {
	if x != nil {
		return x.Network
	}
	return Network_NETWORK_UNSPECIFIED
}

type StopNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeType      NodeType               `protobuf:"varint,1,opt,name=node_type,json=nodeType,proto3,enum=xswallet.NodeType" json:"node_type,omitempty"`
	Graceful      bool                   `protobuf:"varint,2,opt,name=graceful,proto3" json:"graceful,omitempty"` // true = SIGTERM, false = SIGKILL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopNodeRequest) Reset() {
	*x = StopNodeRequest{}
	mi := &file_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopNodeRequest) ProtoMessage() {}

func (x *StopNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopNodeRequest.ProtoReflect.Descriptor instead.
func (*StopNodeRequest) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{2}
}

func (x *StopNodeRequest) GetNodeType() NodeType {
	if x != nil {
		return x.NodeType
	}
	return NodeType_NODE_TYPE_UNSPECIFIED
}

func (x *StopNodeRequest) GetGraceful() bool {
	if x != nil {
		return x.Graceful
	}
	return false
}

type RestartNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeType      NodeType               `protobuf:"varint,1,opt,name=node_type,json=nodeType,proto3,enum=xswallet.NodeType" json:"node_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartNodeRequest) Reset() {
	*x = RestartNodeRequest{}
	mi := &file_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartNodeRequest) ProtoMessage() {}

func (x *RestartNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartNodeRequest.ProtoReflect.Descriptor instead.
func (*RestartNodeRequest) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{3}
}

func (x *RestartNodeRequest) GetNodeType() NodeType {
	if x != nil {
		return x.NodeType
	}
	return NodeType_NODE_TYPE_UNSPECIFIED
}

type GetNodeStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeType      NodeType               `protobuf:"varint,1,opt,name=node_type,json=nodeType,proto3,enum=xswallet.NodeType" json:"node_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeStatusRequest) Reset() {
	*x = GetNodeStatusRequest{}
	mi := &file_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeStatusRequest) ProtoMessage() {}

func (x *GetNodeStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeStatusRequest.ProtoReflect.Descriptor instead.
func (*GetNodeStatusRequest) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{4}
}

func (x *GetNodeStatusRequest) GetNodeType() NodeType {
	if x != nil {
		return x.NodeType
	}
	return NodeType_NODE_TYPE_UNSPECIFIED
}

type GetAllNodeStatusesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllNodeStatusesRequest) Reset() {
	*x = GetAllNodeStatusesRequest{}
	mi := &file_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllNodeStatusesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllNodeStatusesRequest) ProtoMessage() {}

func (x *GetAllNodeStatusesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllNodeStatusesRequest.ProtoReflect.Descriptor instead.
func (*GetAllNodeStatusesRequest) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{5}
}

type GetSyncProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeType      NodeType               `protobuf:"varint,1,opt,name=node_type,json=nodeType,proto3,enum=xswallet.NodeType" json:"node_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSyncProgressRequest) Reset() {
	*x = GetSyncProgressRequest{}
	mi := &file_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSyncProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSyncProgressRequest) ProtoMessage() {}

func (x *GetSyncProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSyncProgressRequest.ProtoReflect.Descriptor instead.
func (*GetSyncProgressRequest) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{6}
}

func (x *GetSyncProgressRequest) GetNodeType() NodeType {
	if x != nil {
		return x.NodeType
	}
	return NodeType_NODE_TYPE_UNSPECIFIED
}

type WatchNodeStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeType      NodeType               `protobuf:"varint,1,opt,name=node_type,json=nodeType,proto3,enum=xswallet.NodeType" json:"node_type,omitempty"` // Vazio = todos
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchNodeStatusRequest) Reset() {
	*x = WatchNodeStatusRequest{}
	mi := &file_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchNodeStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchNodeStatusRequest) ProtoMessage() {}

func (x *WatchNodeStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchNodeStatusRequest.ProtoReflect.Descriptor instead.
func (*WatchNodeStatusRequest) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{7}
}

func (x *WatchNodeStatusRequest) GetNodeType() NodeType {
	if x != nil {
		return x.NodeType
	}
	return NodeType_NODE_TYPE_UNSPECIFIED
}

type WatchLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeType      NodeType               `protobuf:"varint,1,opt,name=node_type,json=nodeType,proto3,enum=xswallet.NodeType" json:"node_type,omitempty"`
	TailLines     int32                  `protobuf:"varint,2,opt,name=tail_lines,json=tailLines,proto3" json:"tail_lines,omitempty"` // Últimas N linhas
	LogLevel      string                 `protobuf:"bytes,3,opt,name=log_level,json=logLevel,proto3" json:"log_level,omitempty"`     // "debug", "info", "warn", "error"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchLogsRequest) Reset() {
	*x = WatchLogsRequest{}
	mi := &file_node_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchLogsRequest) ProtoMessage() {}

func (x *WatchLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchLogsRequest.ProtoReflect.Descriptor instead.
func (*WatchLogsRequest) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{8}
}

func (x *WatchLogsRequest) GetNodeType() NodeType {
	if x != nil {
		return x.NodeType
	}
	return NodeType_NODE_TYPE_UNSPECIFIED
}

func (x *WatchLogsRequest) GetTailLines() int32 {
	if x != nil {
		return x.TailLines
	}
	return 0
}

func (x *WatchLogsRequest) GetLogLevel() string {
	if x != nil {
		return x.LogLevel
	}
	return ""
}

type CheckBinaryStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeType      NodeType               `protobuf:"varint,1,opt,name=node_type,json=nodeType,proto3,enum=xswallet.NodeType" json:"node_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckBinaryStatusRequest) Reset() {
	*x = CheckBinaryStatusRequest{}
	mi := &file_node_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckBinaryStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckBinaryStatusRequest) ProtoMessage() {}

func (x *CheckBinaryStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckBinaryStatusRequest.ProtoReflect.Descriptor instead.
func (*CheckBinaryStatusRequest) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{9}
}

func (x *CheckBinaryStatusRequest) GetNodeType() NodeType {
	if x != nil {
		return x.NodeType
	}
	return NodeType_NODE_TYPE_UNSPECIFIED
}

type DownloadBinaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeType      NodeType               `protobuf:"varint,1,opt,name=node_type,json=nodeType,proto3,enum=xswallet.NodeType" json:"node_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadBinaryRequest) Reset() {
	*x = DownloadBinaryRequest{}
	mi := &file_node_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadBinaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadBinaryRequest) ProtoMessage() {}

func (x *DownloadBinaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadBinaryRequest.ProtoReflect.Descriptor instead.
func (*DownloadBinaryRequest) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{10}
}

func (x *DownloadBinaryRequest) GetNodeType() NodeType {
	if x != nil {
		return x.NodeType
	}
	return NodeType_NODE_TYPE_UNSPECIFIED
}

type VerifyBinaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeType      NodeType               `protobuf:"varint,1,opt,name=node_type,json=nodeType,proto3,enum=xswallet.NodeType" json:"node_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyBinaryRequest) Reset() {
	*x = VerifyBinaryRequest{}
	mi := &file_node_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyBinaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyBinaryRequest) ProtoMessage() {}

func (x *VerifyBinaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyBinaryRequest.ProtoReflect.Descriptor instead.
func (*VerifyBinaryRequest) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{11}
}

func (x *VerifyBinaryRequest) GetNodeType() NodeType {
	if x != nil {
		return x.NodeType
	}
	return NodeType_NODE_TYPE_UNSPECIFIED
}

type NodeStatus struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	NodeType NodeType               `protobuf:"varint,1,opt,name=node_type,json=nodeType,proto3,enum=xswallet.NodeType" json:"node_type,omitempty"`
	State    NodeState              `protobuf:"varint,2,opt,name=state,proto3,enum=xswallet.NodeState" json:"state,omitempty"`
	Network  Network                `protobuf:"varint,3,opt,name=network,proto3,enum=xswallet.Network" json:"network,omitempty"`
	// Versão
	Version string `protobuf:"bytes,10,opt,name=version,proto3" json:"version,omitempty"`
	// Conexões
	PeerCount int32 `protobuf:"varint,20,opt,name=peer_count,json=peerCount,proto3" json:"peer_count,omitempty"`
	// Recursos
	MemoryMb   int64   `protobuf:"varint,30,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	CpuPercent float64 `protobuf:"fixed64,31,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	DiskMb     int64   `protobuf:"varint,32,opt,name=disk_mb,json=diskMb,proto3" json:"disk_mb,omitempty"`
	// Timestamps
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,40,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,41,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	// Erro (se state = ERROR)
	ErrorMessage  string `protobuf:"bytes,50,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeStatus) Reset() {
	*x = NodeStatus{}
	mi := &file_node_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatus) ProtoMessage() {}

func (x *NodeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatus.ProtoReflect.Descriptor instead.
func (*NodeStatus) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{12}
}

func (x *NodeStatus) GetNodeType() NodeType {
	if x != nil {
		return x.NodeType
	}
	return NodeType_NODE_TYPE_UNSPECIFIED
}

func (x *NodeStatus) GetState() NodeState {
	if x != nil {
		return x.State
	}
	return NodeState_NODE_STATE_UNSPECIFIED
}

func (x *NodeStatus) GetNetwork() Network {
	if x != nil {
		return x.Network
	}
	return Network_NETWORK_UNSPECIFIED
}

func (x *NodeStatus) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *NodeStatus) GetPeerCount() int32 {
	if x != nil {
		return x.PeerCount
	}
	return 0
}

func (x *NodeStatus) GetMemoryMb() int64 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *NodeStatus) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *NodeStatus) GetDiskMb() int64 {
	if x != nil {
		return x.DiskMb
	}
	return 0
}

func (x *NodeStatus) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *NodeStatus) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *NodeStatus) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type AllNodeStatusesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bitcoind      *NodeStatus            `protobuf:"bytes,1,opt,name=bitcoind,proto3" json:"bitcoind,omitempty"`
	Elementsd     *NodeStatus            `protobuf:"bytes,2,opt,name=elementsd,proto3" json:"elementsd,omitempty"`
	Lnd           *NodeStatus            `protobuf:"bytes,3,opt,name=lnd,proto3" json:"lnd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllNodeStatusesResponse) Reset() {
	*x = AllNodeStatusesResponse{}
	mi := &file_node_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllNodeStatusesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllNodeStatusesResponse) ProtoMessage() {}

func (x *AllNodeStatusesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllNodeStatusesResponse.ProtoReflect.Descriptor instead.
func (*AllNodeStatusesResponse) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{13}
}

func (x *AllNodeStatusesResponse) GetBitcoind() *NodeStatus {
	if x != nil {
		return x.Bitcoind
	}
	return nil
}

func (x *AllNodeStatusesResponse) GetElementsd() *NodeStatus {
	if x != nil {
		return x.Elementsd
	}
	return nil
}

func (x *AllNodeStatusesResponse) GetLnd() *NodeStatus {
	if x != nil {
		return x.Lnd
	}
	return nil
}

type SyncProgress struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeType        NodeType               `protobuf:"varint,1,opt,name=node_type,json=nodeType,proto3,enum=xswallet.NodeType" json:"node_type,omitempty"`
	Synced          bool                   `protobuf:"varint,2,opt,name=synced,proto3" json:"synced,omitempty"`
	CurrentHeight   uint32                 `protobuf:"varint,3,opt,name=current_height,json=currentHeight,proto3" json:"current_height,omitempty"`
	TargetHeight    uint32                 `protobuf:"varint,4,opt,name=target_height,json=targetHeight,proto3" json:"target_height,omitempty"`
	ProgressPercent float64                `protobuf:"fixed64,5,opt,name=progress_percent,json=progressPercent,proto3" json:"progress_percent,omitempty"`
	Eta             string                 `protobuf:"bytes,6,opt,name=eta,proto3" json:"eta,omitempty"` // Estimativa de conclusão
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SyncProgress) Reset() {
	*x = SyncProgress{}
	mi := &file_node_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncProgress) ProtoMessage() {}

func (x *SyncProgress) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncProgress.ProtoReflect.Descriptor instead.
func (*SyncProgress) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{14}
}

func (x *SyncProgress) GetNodeType() NodeType {
	if x != nil {
		return x.NodeType
	}
	return NodeType_NODE_TYPE_UNSPECIFIED
}

func (x *SyncProgress) GetSynced() bool {
	if x != nil {
		return x.Synced
	}
	return false
}

func (x *SyncProgress) GetCurrentHeight() uint32 {
	if x != nil {
		return x.CurrentHeight
	}
	return 0
}

func (x *SyncProgress) GetTargetHeight() uint32 {
	if x != nil {
		return x.TargetHeight
	}
	return 0
}

func (x *SyncProgress) GetProgressPercent() float64 {
	if x != nil {
		return x.ProgressPercent
	}
	return 0
}

func (x *SyncProgress) GetEta() string {
	if x != nil {
		return x.Eta
	}
	return ""
}

type NodeStatusUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeType      NodeType               `protobuf:"varint,1,opt,name=node_type,json=nodeType,proto3,enum=xswallet.NodeType" json:"node_type,omitempty"`
	PreviousState NodeState              `protobuf:"varint,2,opt,name=previous_state,json=previousState,proto3,enum=xswallet.NodeState" json:"previous_state,omitempty"`
	CurrentState  NodeState              `protobuf:"varint,3,opt,name=current_state,json=currentState,proto3,enum=xswallet.NodeState" json:"current_state,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeStatusUpdate) Reset() {
	*x = NodeStatusUpdate{}
	mi := &file_node_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatusUpdate) ProtoMessage() {}

func (x *NodeStatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatusUpdate.ProtoReflect.Descriptor instead.
func (*NodeStatusUpdate) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{15}
}

func (x *NodeStatusUpdate) GetNodeType() NodeType {
	if x != nil {
		return x.NodeType
	}
	return NodeType_NODE_TYPE_UNSPECIFIED
}

func (x *NodeStatusUpdate) GetPreviousState() NodeState {
	if x != nil {
		return x.PreviousState
	}
	return NodeState_NODE_STATE_UNSPECIFIED
}

func (x *NodeStatusUpdate) GetCurrentState() NodeState {
	if x != nil {
		return x.CurrentState
	}
	return NodeState_NODE_STATE_UNSPECIFIED
}

func (x *NodeStatusUpdate) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeType      NodeType               `protobuf:"varint,1,opt,name=node_type,json=nodeType,proto3,enum=xswallet.NodeType" json:"node_type,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_node_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{16}
}

func (x *LogEntry) GetNodeType() NodeType {
	if x != nil {
		return x.NodeType
	}
	return NodeType_NODE_TYPE_UNSPECIFIED
}

func (x *LogEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type BinaryStatus struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NodeType         NodeType               `protobuf:"varint,1,opt,name=node_type,json=nodeType,proto3,enum=xswallet.NodeType" json:"node_type,omitempty"`
	Installed        bool                   `protobuf:"varint,2,opt,name=installed,proto3" json:"installed,omitempty"`
	InstalledVersion string                 `protobuf:"bytes,3,opt,name=installed_version,json=installedVersion,proto3" json:"installed_version,omitempty"`
	LatestVersion    string                 `protobuf:"bytes,4,opt,name=latest_version,json=latestVersion,proto3" json:"latest_version,omitempty"`
	UpdateAvailable  bool                   `protobuf:"varint,5,opt,name=update_available,json=updateAvailable,proto3" json:"update_available,omitempty"`
	Verified         bool                   `protobuf:"varint,6,opt,name=verified,proto3" json:"verified,omitempty"` // SHA256 verificado
	BinaryPath       string                 `protobuf:"bytes,7,opt,name=binary_path,json=binaryPath,proto3" json:"binary_path,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BinaryStatus) Reset() {
	*x = BinaryStatus{}
	mi := &file_node_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BinaryStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinaryStatus) ProtoMessage() {}

func (x *BinaryStatus) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BinaryStatus.ProtoReflect.Descriptor instead.
func (*BinaryStatus) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{17}
}

func (x *BinaryStatus) GetNodeType() NodeType {
	if x != nil {
		return x.NodeType
	}
	return NodeType_NODE_TYPE_UNSPECIFIED
}

func (x *BinaryStatus) GetInstalled() bool {
	if x != nil {
		return x.Installed
	}
	return false
}

func (x *BinaryStatus) GetInstalledVersion() string {
	if x != nil {
		return x.InstalledVersion
	}
	return ""
}

func (x *BinaryStatus) GetLatestVersion() string {
	if x != nil {
		return x.LatestVersion
	}
	return ""
}

func (x *BinaryStatus) GetUpdateAvailable() bool {
	if x != nil {
		return x.UpdateAvailable
	}
	return false
}

func (x *BinaryStatus) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *BinaryStatus) GetBinaryPath() string {
	if x != nil {
		return x.BinaryPath
	}
	return ""
}

type DownloadProgress struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeType        NodeType               `protobuf:"varint,1,opt,name=node_type,json=nodeType,proto3,enum=xswallet.NodeType" json:"node_type,omitempty"`
	BytesDownloaded uint64                 `protobuf:"varint,2,opt,name=bytes_downloaded,json=bytesDownloaded,proto3" json:"bytes_downloaded,omitempty"`
	TotalBytes      uint64                 `protobuf:"varint,3,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	ProgressPercent float64                `protobuf:"fixed64,4,opt,name=progress_percent,json=progressPercent,proto3" json:"progress_percent,omitempty"`
	Stage           string                 `protobuf:"bytes,5,opt,name=stage,proto3" json:"stage,omitempty"` // "downloading", "extracting", "verifying"
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DownloadProgress) Reset() {
	*x = DownloadProgress{}
	mi := &file_node_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadProgress) ProtoMessage() {}

func (x *DownloadProgress) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadProgress.ProtoReflect.Descriptor instead.
func (*DownloadProgress) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{18}
}

func (x *DownloadProgress) GetNodeType() NodeType {
	if x != nil {
		return x.NodeType
	}
	return NodeType_NODE_TYPE_UNSPECIFIED
}

func (x *DownloadProgress) GetBytesDownloaded() uint64 {
	if x != nil {
		return x.BytesDownloaded
	}
	return 0
}

func (x *DownloadProgress) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *DownloadProgress) GetProgressPercent() float64 {
	if x != nil {
		return x.ProgressPercent
	}
	return 0
}

func (x *DownloadProgress) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

type VerifyBinaryResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeType        NodeType               `protobuf:"varint,1,opt,name=node_type,json=nodeType,proto3,enum=xswallet.NodeType" json:"node_type,omitempty"`
	Verified        bool                   `protobuf:"varint,2,opt,name=verified,proto3" json:"verified,omitempty"`
	ExpectedHash    string                 `protobuf:"bytes,3,opt,name=expected_hash,json=expectedHash,proto3" json:"expected_hash,omitempty"`
	ActualHash      string                 `protobuf:"bytes,4,opt,name=actual_hash,json=actualHash,proto3" json:"actual_hash,omitempty"`
	SignatureStatus string                 `protobuf:"bytes,5,opt,name=signature_status,json=signatureStatus,proto3" json:"signature_status,omitempty"` // "valid", "invalid", "not_found"
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VerifyBinaryResponse) Reset() {
	*x = VerifyBinaryResponse{}
	mi := &file_node_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyBinaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyBinaryResponse) ProtoMessage() {}

func (x *VerifyBinaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyBinaryResponse.ProtoReflect.Descriptor instead.
func (*VerifyBinaryResponse) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{19}
}

func (x *VerifyBinaryResponse) GetNodeType() NodeType {
	if x != nil {
		return x.NodeType
	}
	return NodeType_NODE_TYPE_UNSPECIFIED
}

func (x *VerifyBinaryResponse) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *VerifyBinaryResponse) GetExpectedHash() string {
	if x != nil {
		return x.ExpectedHash
	}
	return ""
}

func (x *VerifyBinaryResponse) GetActualHash() string {
	if x != nil {
		return x.ActualHash
	}
	return ""
}

func (x *VerifyBinaryResponse) GetSignatureStatus() string {
	if x != nil {
		return x.SignatureStatus
	}
	return ""
}

var File_node_proto protoreflect.FileDescriptor

const file_node_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"node.proto\x12\bxswallet\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\fcommon.proto\" \n" +
	"\x1eGetPlatformCapabilitiesRequest\"p\n" +
	"\x10StartNodeRequest\x12/\n" +
	"\tnode_type\x18\x01 \x01(\x0e2\x12.xswallet.NodeTypeR\bnodeType\x12+\n" +
	"\anetwork\x18\x02 \x01(\x0e2\x11.xswallet.NetworkR\anetwork\"^\n" +
	"\x0fStopNodeRequest\x12/\n" +
	"\tnode_type\x18\x01 \x01(\x0e2\x12.xswallet.NodeTypeR\bnodeType\x12\x1a\n" +
	"\bgraceful\x18\x02 \x01(\bR\bgraceful\"E\n" +
	"\x12RestartNodeRequest\x12/\n" +
	"\tnode_type\x18\x01 \x01(\x0e2\x12.xswallet.NodeTypeR\bnodeType\"G\n" +
	"\x14GetNodeStatusRequest\x12/\n" +
	"\tnode_type\x18\x01 \x01(\x0e2\x12.xswallet.NodeTypeR\bnodeType\"\x1b\n" +
	"\x19GetAllNodeStatusesRequest\"I\n" +
	"\x16GetSyncProgressRequest\x12/\n" +
	"\tnode_type\x18\x01 \x01(\x0e2\x12.xswallet.NodeTypeR\bnodeType\"I\n" +
	"\x16WatchNodeStatusRequest\x12/\n" +
	"\tnode_type\x18\x01 \x01(\x0e2\x12.xswallet.NodeTypeR\bnodeType\"\x7f\n" +
	"\x10WatchLogsRequest\x12/\n" +
	"\tnode_type\x18\x01 \x01(\x0e2\x12.xswallet.NodeTypeR\bnodeType\x12\x1d\n" +
	"\n" +
	"tail_lines\x18\x02 \x01(\x05R\ttailLines\x12\x1b\n" +
	"\tlog_level\x18\x03 \x01(\tR\blogLevel\"K\n" +
	"\x18CheckBinaryStatusRequest\x12/\n" +
	"\tnode_type\x18\x01 \x01(\x0e2\x12.xswallet.NodeTypeR\bnodeType\"H\n" +
	"\x15DownloadBinaryRequest\x12/\n" +
	"\tnode_type\x18\x01 \x01(\x0e2\x12.xswallet.NodeTypeR\bnodeType\"F\n" +
	"\x13VerifyBinaryRequest\x12/\n" +
	"\tnode_type\x18\x01 \x01(\x0e2\x12.xswallet.NodeTypeR\bnodeType\"\xac\x03\n" +
	"\n" +
	"NodeStatus\x12/\n" +
	"\tnode_type\x18\x01 \x01(\x0e2\x12.xswallet.NodeTypeR\bnodeType\x12)\n" +
	"\x05state\x18\x02 \x01(\x0e2\x13.xswallet.NodeStateR\x05state\x12+\n" +
	"\anetwork\x18\x03 \x01(\x0e2\x11.xswallet.NetworkR\anetwork\x12\x18\n" +
	"\aversion\x18\n" +
	" \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"peer_count\x18\x14 \x01(\x05R\tpeerCount\x12\x1b\n" +
	"\tmemory_mb\x18\x1e \x01(\x03R\bmemoryMb\x12\x1f\n" +
	"\vcpu_percent\x18\x1f \x01(\x01R\n" +
	"cpuPercent\x12\x17\n" +
	"\adisk_mb\x18  \x01(\x03R\x06diskMb\x129\n" +
	"\n" +
	"started_at\x18( \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12%\n" +
	"\x0euptime_seconds\x18) \x01(\x03R\ruptimeSeconds\x12#\n" +
	"\rerror_message\x182 \x01(\tR\ferrorMessage\"\xa7\x01\n" +
	"\x17AllNodeStatusesResponse\x120\n" +
	"\bbitcoind\x18\x01 \x01(\v2\x14.xswallet.NodeStatusR\bbitcoind\x122\n" +
	"\telementsd\x18\x02 \x01(\v2\x14.xswallet.NodeStatusR\telementsd\x12&\n" +
	"\x03lnd\x18\x03 \x01(\v2\x14.xswallet.NodeStatusR\x03lnd\"\xe0\x01\n" +
	"\fSyncProgress\x12/\n" +
	"\tnode_type\x18\x01 \x01(\x0e2\x12.xswallet.NodeTypeR\bnodeType\x12\x16\n" +
	"\x06synced\x18\x02 \x01(\bR\x06synced\x12%\n" +
	"\x0ecurrent_height\x18\x03 \x01(\rR\rcurrentHeight\x12#\n" +
	"\rtarget_height\x18\x04 \x01(\rR\ftargetHeight\x12)\n" +
	"\x10progress_percent\x18\x05 \x01(\x01R\x0fprogressPercent\x12\x10\n" +
	"\x03eta\x18\x06 \x01(\tR\x03eta\"\xf3\x01\n" +
	"\x10NodeStatusUpdate\x12/\n" +
	"\tnode_type\x18\x01 \x01(\x0e2\x12.xswallet.NodeTypeR\bnodeType\x12:\n" +
	"\x0eprevious_state\x18\x02 \x01(\x0e2\x13.xswallet.NodeStateR\rpreviousState\x128\n" +
	"\rcurrent_state\x18\x03 \x01(\x0e2\x13.xswallet.NodeStateR\fcurrentState\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xa5\x01\n" +
	"\bLogEntry\x12/\n" +
	"\tnode_type\x18\x01 \x01(\x0e2\x12.xswallet.NodeTypeR\bnodeType\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x99\x02\n" +
	"\fBinaryStatus\x12/\n" +
	"\tnode_type\x18\x01 \x01(\x0e2\x12.xswallet.NodeTypeR\bnodeType\x12\x1c\n" +
	"\tinstalled\x18\x02 \x01(\bR\tinstalled\x12+\n" +
	"\x11installed_version\x18\x03 \x01(\tR\x10installedVersion\x12%\n" +
	"\x0elatest_version\x18\x04 \x01(\tR\rlatestVersion\x12)\n" +
	"\x10update_available\x18\x05 \x01(\bR\x0fupdateAvailable\x12\x1a\n" +
	"\bverified\x18\x06 \x01(\bR\bverified\x12\x1f\n" +
	"\vbinary_path\x18\a \x01(\tR\n" +
	"binaryPath\"\xd0\x01\n" +
	"\x10DownloadProgress\x12/\n" +
	"\tnode_type\x18\x01 \x01(\x0e2\x12.xswallet.NodeTypeR\bnodeType\x12)\n" +
	"\x10bytes_downloaded\x18\x02 \x01(\x04R\x0fbytesDownloaded\x12\x1f\n" +
	"\vtotal_bytes\x18\x03 \x01(\x04R\n" +
	"totalBytes\x12)\n" +
	"\x10progress_percent\x18\x04 \x01(\x01R\x0fprogressPercent\x12\x14\n" +
	"\x05stage\x18\x05 \x01(\tR\x05stage\"\xd4\x01\n" +
	"\x14VerifyBinaryResponse\x12/\n" +
	"\tnode_type\x18\x01 \x01(\x0e2\x12.xswallet.NodeTypeR\bnodeType\x12\x1a\n" +
	"\bverified\x18\x02 \x01(\bR\bverified\x12#\n" +
	"\rexpected_hash\x18\x03 \x01(\tR\fexpectedHash\x12\x1f\n" +
	"\vactual_hash\x18\x04 \x01(\tR\n" +
	"actualHash\x12)\n" +
	"\x10signature_status\x18\x05 \x01(\tR\x0fsignatureStatus*i\n" +
	"\bNodeType\x12\x19\n" +
	"\x15NODE_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12NODE_TYPE_BITCOIND\x10\x01\x12\x17\n" +
	"\x13NODE_TYPE_ELEMENTSD\x10\x02\x12\x11\n" +
	"\rNODE_TYPE_LND\x10\x03*\xd5\x01\n" +
	"\tNodeState\x12\x1a\n" +
	"\x16NODE_STATE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18NODE_STATE_NOT_INSTALLED\x10\x01\x12\x16\n" +
	"\x12NODE_STATE_STOPPED\x10\x02\x12\x17\n" +
	"\x13NODE_STATE_STARTING\x10\x03\x12\x16\n" +
	"\x12NODE_STATE_SYNCING\x10\x04\x12\x16\n" +
	"\x12NODE_STATE_RUNNING\x10\x05\x12\x17\n" +
	"\x13NODE_STATE_STOPPING\x10\x06\x12\x14\n" +
	"\x10NODE_STATE_ERROR\x10\a2\xa6\a\n" +
	"\vNodeService\x12c\n" +
	"\x17GetPlatformCapabilities\x12(.xswallet.GetPlatformCapabilitiesRequest\x1a\x1e.xswallet.PlatformCapabilities\x12=\n" +
	"\tStartNode\x12\x1a.xswallet.StartNodeRequest\x1a\x14.xswallet.NodeStatus\x12;\n" +
	"\bStopNode\x12\x19.xswallet.StopNodeRequest\x1a\x14.xswallet.NodeStatus\x12A\n" +
	"\vRestartNode\x12\x1c.xswallet.RestartNodeRequest\x1a\x14.xswallet.NodeStatus\x12E\n" +
	"\rGetNodeStatus\x12\x1e.xswallet.GetNodeStatusRequest\x1a\x14.xswallet.NodeStatus\x12\\\n" +
	"\x12GetAllNodeStatuses\x12#.xswallet.GetAllNodeStatusesRequest\x1a!.xswallet.AllNodeStatusesResponse\x12K\n" +
	"\x0fGetSyncProgress\x12 .xswallet.GetSyncProgressRequest\x1a\x16.xswallet.SyncProgress\x12Q\n" +
	"\x0fWatchNodeStatus\x12 .xswallet.WatchNodeStatusRequest\x1a\x1a.xswallet.NodeStatusUpdate0\x01\x12=\n" +
	"\tWatchLogs\x12\x1a.xswallet.WatchLogsRequest\x1a\x12.xswallet.LogEntry0\x01\x12O\n" +
	"\x11CheckBinaryStatus\x12\".xswallet.CheckBinaryStatusRequest\x1a\x16.xswallet.BinaryStatus\x12O\n" +
	"\x0eDownloadBinary\x12\x1f.xswallet.DownloadBinaryRequest\x1a\x1a.xswallet.DownloadProgress0\x01\x12M\n" +
	"\fVerifyBinary\x12\x1d.xswallet.VerifyBinaryRequest\x1a\x1e.xswallet.VerifyBinaryResponseB#Z!github.com/xs-wallet/xscore/protob\x06proto3"

var (
	file_node_proto_rawDescOnce sync.Once
	file_node_proto_rawDescData []byte
)

func file_node_proto_rawDescGZIP() []byte {
	file_node_proto_rawDescOnce.Do(func() {
		file_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_node_proto_rawDesc), len(file_node_proto_rawDesc)))
	})
	return file_node_proto_rawDescData
}

var file_node_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_node_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_node_proto_goTypes = []any{
	(NodeType)(0),                          // 0: xswallet.NodeType
	(NodeState)(0),                         // 1: xswallet.NodeState
	(*GetPlatformCapabilitiesRequest)(nil), // 2: xswallet.GetPlatformCapabilitiesRequest
	(*StartNodeRequest)(nil),               // 3: xswallet.StartNodeRequest
	(*StopNodeRequest)(nil),                // 4: xswallet.StopNodeRequest
	(*RestartNodeRequest)(nil),             // 5: xswallet.RestartNodeRequest
	(*GetNodeStatusRequest)(nil),           // 6: xswallet.GetNodeStatusRequest
	(*GetAllNodeStatusesRequest)(nil),      // 7: xswallet.GetAllNodeStatusesRequest
	(*GetSyncProgressRequest)(nil),         // 8: xswallet.GetSyncProgressRequest
	(*WatchNodeStatusRequest)(nil),         // 9: xswallet.WatchNodeStatusRequest
	(*WatchLogsRequest)(nil),               // 10: xswallet.WatchLogsRequest
	(*CheckBinaryStatusRequest)(nil),       // 11: xswallet.CheckBinaryStatusRequest
	(*DownloadBinaryRequest)(nil),          // 12: xswallet.DownloadBinaryRequest
	(*VerifyBinaryRequest)(nil),            // 13: xswallet.VerifyBinaryRequest
	(*NodeStatus)(nil),                     // 14: xswallet.NodeStatus
	(*AllNodeStatusesResponse)(nil),        // 15: xswallet.AllNodeStatusesResponse
	(*SyncProgress)(nil),                   // 16: xswallet.SyncProgress
	(*NodeStatusUpdate)(nil),               // 17: xswallet.NodeStatusUpdate
	(*LogEntry)(nil),                       // 18: xswallet.LogEntry
	(*BinaryStatus)(nil),                   // 19: xswallet.BinaryStatus
	(*DownloadProgress)(nil),               // 20: xswallet.DownloadProgress
	(*VerifyBinaryResponse)(nil),           // 21: xswallet.VerifyBinaryResponse
	(Network)(0),                           // 22: xswallet.Network
	(*timestamppb.Timestamp)(nil),          // 23: google.protobuf.Timestamp
	(*PlatformCapabilities)(nil),           // 24: xswallet.PlatformCapabilities
}
var file_node_proto_depIdxs = []int32{
	0,  // 0: xswallet.StartNodeRequest.node_type:type_name -> xswallet.NodeType
	22, // 1: xswallet.StartNodeRequest.network:type_name -> xswallet.Network
	0,  // 2: xswallet.StopNodeRequest.node_type:type_name -> xswallet.NodeType
	0,  // 3: xswallet.RestartNodeRequest.node_type:type_name -> xswallet.NodeType
	0,  // 4: xswallet.GetNodeStatusRequest.node_type:type_name -> xswallet.NodeType
	0,  // 5: xswallet.GetSyncProgressRequest.node_type:type_name -> xswallet.NodeType
	0,  // 6: xswallet.WatchNodeStatusRequest.node_type:type_name -> xswallet.NodeType
	0,  // 7: xswallet.WatchLogsRequest.node_type:type_name -> xswallet.NodeType
	0,  // 8: xswallet.CheckBinaryStatusRequest.node_type:type_name -> xswallet.NodeType
	0,  // 9: xswallet.DownloadBinaryRequest.node_type:type_name -> xswallet.NodeType
	0,  // 10: xswallet.VerifyBinaryRequest.node_type:type_name -> xswallet.NodeType
	0,  // 11: xswallet.NodeStatus.node_type:type_name -> xswallet.NodeType
	1,  // 12: xswallet.NodeStatus.state:type_name -> xswallet.NodeState
	22, // 13: xswallet.NodeStatus.network:type_name -> xswallet.Network
	23, // 14: xswallet.NodeStatus.started_at:type_name -> google.protobuf.Timestamp
	14, // 15: xswallet.AllNodeStatusesResponse.bitcoind:type_name -> xswallet.NodeStatus
	14, // 16: xswallet.AllNodeStatusesResponse.elementsd:type_name -> xswallet.NodeStatus
	14, // 17: xswallet.AllNodeStatusesResponse.lnd:type_name -> xswallet.NodeStatus
	0,  // 18: xswallet.SyncProgress.node_type:type_name -> xswallet.NodeType
	0,  // 19: xswallet.NodeStatusUpdate.node_type:type_name -> xswallet.NodeType
	1,  // 20: xswallet.NodeStatusUpdate.previous_state:type_name -> xswallet.NodeState
	1,  // 21: xswallet.NodeStatusUpdate.current_state:type_name -> xswallet.NodeState
	23, // 22: xswallet.NodeStatusUpdate.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 23: xswallet.LogEntry.node_type:type_name -> xswallet.NodeType
	23, // 24: xswallet.LogEntry.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 25: xswallet.BinaryStatus.node_type:type_name -> xswallet.NodeType
	0,  // 26: xswallet.DownloadProgress.node_type:type_name -> xswallet.NodeType
	0,  // 27: xswallet.VerifyBinaryResponse.node_type:type_name -> xswallet.NodeType
	2,  // 28: xswallet.NodeService.GetPlatformCapabilities:input_type -> xswallet.GetPlatformCapabilitiesRequest
	3,  // 29: xswallet.NodeService.StartNode:input_type -> xswallet.StartNodeRequest
	4,  // 30: xswallet.NodeService.StopNode:input_type -> xswallet.StopNodeRequest
	5,  // 31: xswallet.NodeService.RestartNode:input_type -> xswallet.RestartNodeRequest
	6,  // 32: xswallet.NodeService.GetNodeStatus:input_type -> xswallet.GetNodeStatusRequest
	7,  // 33: xswallet.NodeService.GetAllNodeStatuses:input_type -> xswallet.GetAllNodeStatusesRequest
	8,  // 34: xswallet.NodeService.GetSyncProgress:input_type -> xswallet.GetSyncProgressRequest
	9,  // 35: xswallet.NodeService.WatchNodeStatus:input_type -> xswallet.WatchNodeStatusRequest
	10, // 36: xswallet.NodeService.WatchLogs:input_type -> xswallet.WatchLogsRequest
	11, // 37: xswallet.NodeService.CheckBinaryStatus:input_type -> xswallet.CheckBinaryStatusRequest
	12, // 38: xswallet.NodeService.DownloadBinary:input_type -> xswallet.DownloadBinaryRequest
	13, // 39: xswallet.NodeService.VerifyBinary:input_type -> xswallet.VerifyBinaryRequest
	24, // 40: xswallet.NodeService.GetPlatformCapabilities:output_type -> xswallet.PlatformCapabilities
	14, // 41: xswallet.NodeService.StartNode:output_type -> xswallet.NodeStatus
	14, // 42: xswallet.NodeService.StopNode:output_type -> xswallet.NodeStatus
	14, // 43: xswallet.NodeService.RestartNode:output_type -> xswallet.NodeStatus
	14, // 44: xswallet.NodeService.GetNodeStatus:output_type -> xswallet.NodeStatus
	15, // 45: xswallet.NodeService.GetAllNodeStatuses:output_type -> xswallet.AllNodeStatusesResponse
	16, // 46: xswallet.NodeService.GetSyncProgress:output_type -> xswallet.SyncProgress
	17, // 47: xswallet.NodeService.WatchNodeStatus:output_type -> xswallet.NodeStatusUpdate
	18, // 48: xswallet.NodeService.WatchLogs:output_type -> xswallet.LogEntry
	19, // 49: xswallet.NodeService.CheckBinaryStatus:output_type -> xswallet.BinaryStatus
	20, // 50: xswallet.NodeService.DownloadBinary:output_type -> xswallet.DownloadProgress
	21, // 51: xswallet.NodeService.VerifyBinary:output_type -> xswallet.VerifyBinaryResponse
	40, // [40:52] is the sub-list for method output_type
	28, // [28:40] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_node_proto_init() }
func file_node_proto_init() {
	if File_node_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_node_proto_rawDesc), len(file_node_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_node_proto_goTypes,
		DependencyIndexes: file_node_proto_depIdxs,
		EnumInfos:         file_node_proto_enumTypes,
		MessageInfos:      file_node_proto_msgTypes,
	}.Build()
	File_node_proto = out.File
	file_node_proto_goTypes = nil
	file_node_proto_depIdxs = nil
}
