// XS Wallet - Node Service Protocol
// Gerenciamento de nodes embarcados (bitcoind, elementsd, LND)

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: node.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeService_GetPlatformCapabilities_FullMethodName = "/xswallet.NodeService/GetPlatformCapabilities"
	NodeService_StartNode_FullMethodName               = "/xswallet.NodeService/StartNode"
	NodeService_StopNode_FullMethodName                = "/xswallet.NodeService/StopNode"
	NodeService_RestartNode_FullMethodName             = "/xswallet.NodeService/RestartNode"
	NodeService_GetNodeStatus_FullMethodName           = "/xswallet.NodeService/GetNodeStatus"
	NodeService_GetAllNodeStatuses_FullMethodName      = "/xswallet.NodeService/GetAllNodeStatuses"
	NodeService_GetSyncProgress_FullMethodName         = "/xswallet.NodeService/GetSyncProgress"
	NodeService_WatchNodeStatus_FullMethodName         = "/xswallet.NodeService/WatchNodeStatus"
	NodeService_WatchLogs_FullMethodName               = "/xswallet.NodeService/WatchLogs"
	NodeService_CheckBinaryStatus_FullMethodName       = "/xswallet.NodeService/CheckBinaryStatus"
	NodeService_DownloadBinary_FullMethodName          = "/xswallet.NodeService/DownloadBinary"
	NodeService_VerifyBinary_FullMethodName            = "/xswallet.NodeService/VerifyBinary"
)

// NodeServiceClient is the client API for NodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeServiceClient interface {
	// Platform
	GetPlatformCapabilities(ctx context.Context, in *GetPlatformCapabilitiesRequest, opts ...grpc.CallOption) (*PlatformCapabilities, error)
	// Lifecycle (desktop only se can_spawn_nodes = true)
	StartNode(ctx context.Context, in *StartNodeRequest, opts ...grpc.CallOption) (*NodeStatus, error)
	StopNode(ctx context.Context, in *StopNodeRequest, opts ...grpc.CallOption) (*NodeStatus, error)
	RestartNode(ctx context.Context, in *RestartNodeRequest, opts ...grpc.CallOption) (*NodeStatus, error)
	// Status (funciona em desktop e mobile)
	GetNodeStatus(ctx context.Context, in *GetNodeStatusRequest, opts ...grpc.CallOption) (*NodeStatus, error)
	GetAllNodeStatuses(ctx context.Context, in *GetAllNodeStatusesRequest, opts ...grpc.CallOption) (*AllNodeStatusesResponse, error)
	// Sync
	GetSyncProgress(ctx context.Context, in *GetSyncProgressRequest, opts ...grpc.CallOption) (*SyncProgress, error)
	// Streaming
	WatchNodeStatus(ctx context.Context, in *WatchNodeStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NodeStatusUpdate], error)
	WatchLogs(ctx context.Context, in *WatchLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEntry], error)
	// Binary management (desktop only se can_download_binaries = true)
	CheckBinaryStatus(ctx context.Context, in *CheckBinaryStatusRequest, opts ...grpc.CallOption) (*BinaryStatus, error)
	DownloadBinary(ctx context.Context, in *DownloadBinaryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadProgress], error)
	VerifyBinary(ctx context.Context, in *VerifyBinaryRequest, opts ...grpc.CallOption) (*VerifyBinaryResponse, error)
}

type nodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeServiceClient(cc grpc.ClientConnInterface) NodeServiceClient {
	return &nodeServiceClient{cc}
}

func (c *nodeServiceClient) GetPlatformCapabilities(ctx context.Context, in *GetPlatformCapabilitiesRequest, opts ...grpc.CallOption) (*PlatformCapabilities, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlatformCapabilities)
	err := c.cc.Invoke(ctx, NodeService_GetPlatformCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) StartNode(ctx context.Context, in *StartNodeRequest, opts ...grpc.CallOption) (*NodeStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeStatus)
	err := c.cc.Invoke(ctx, NodeService_StartNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) StopNode(ctx context.Context, in *StopNodeRequest, opts ...grpc.CallOption) (*NodeStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeStatus)
	err := c.cc.Invoke(ctx, NodeService_StopNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) RestartNode(ctx context.Context, in *RestartNodeRequest, opts ...grpc.CallOption) (*NodeStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeStatus)
	err := c.cc.Invoke(ctx, NodeService_RestartNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) GetNodeStatus(ctx context.Context, in *GetNodeStatusRequest, opts ...grpc.CallOption) (*NodeStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeStatus)
	err := c.cc.Invoke(ctx, NodeService_GetNodeStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) GetAllNodeStatuses(ctx context.Context, in *GetAllNodeStatusesRequest, opts ...grpc.CallOption) (*AllNodeStatusesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AllNodeStatusesResponse)
	err := c.cc.Invoke(ctx, NodeService_GetAllNodeStatuses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) GetSyncProgress(ctx context.Context, in *GetSyncProgressRequest, opts ...grpc.CallOption) (*SyncProgress, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncProgress)
	err := c.cc.Invoke(ctx, NodeService_GetSyncProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) WatchNodeStatus(ctx context.Context, in *WatchNodeStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NodeStatusUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeService_ServiceDesc.Streams[0], NodeService_WatchNodeStatus_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchNodeStatusRequest, NodeStatusUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_WatchNodeStatusClient = grpc.ServerStreamingClient[NodeStatusUpdate]

func (c *nodeServiceClient) WatchLogs(ctx context.Context, in *WatchLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeService_ServiceDesc.Streams[1], NodeService_WatchLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchLogsRequest, LogEntry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_WatchLogsClient = grpc.ServerStreamingClient[LogEntry]

func (c *nodeServiceClient) CheckBinaryStatus(ctx context.Context, in *CheckBinaryStatusRequest, opts ...grpc.CallOption) (*BinaryStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BinaryStatus)
	err := c.cc.Invoke(ctx, NodeService_CheckBinaryStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) DownloadBinary(ctx context.Context, in *DownloadBinaryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeService_ServiceDesc.Streams[2], NodeService_DownloadBinary_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DownloadBinaryRequest, DownloadProgress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_DownloadBinaryClient = grpc.ServerStreamingClient[DownloadProgress]

func (c *nodeServiceClient) VerifyBinary(ctx context.Context, in *VerifyBinaryRequest, opts ...grpc.CallOption) (*VerifyBinaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyBinaryResponse)
	err := c.cc.Invoke(ctx, NodeService_VerifyBinary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeServiceServer is the server API for NodeService service.
// All implementations must embed UnimplementedNodeServiceServer
// for forward compatibility.
type NodeServiceServer interface {
	// Platform
	GetPlatformCapabilities(context.Context, *GetPlatformCapabilitiesRequest) (*PlatformCapabilities, error)
	// Lifecycle (desktop only se can_spawn_nodes = true)
	StartNode(context.Context, *StartNodeRequest) (*NodeStatus, error)
	StopNode(context.Context, *StopNodeRequest) (*NodeStatus, error)
	RestartNode(context.Context, *RestartNodeRequest) (*NodeStatus, error)
	// Status (funciona em desktop e mobile)
	GetNodeStatus(context.Context, *GetNodeStatusRequest) (*NodeStatus, error)
	GetAllNodeStatuses(context.Context, *GetAllNodeStatusesRequest) (*AllNodeStatusesResponse, error)
	// Sync
	GetSyncProgress(context.Context, *GetSyncProgressRequest) (*SyncProgress, error)
	// Streaming
	WatchNodeStatus(*WatchNodeStatusRequest, grpc.ServerStreamingServer[NodeStatusUpdate]) error
	WatchLogs(*WatchLogsRequest, grpc.ServerStreamingServer[LogEntry]) error
	// Binary management (desktop only se can_download_binaries = true)
	CheckBinaryStatus(context.Context, *CheckBinaryStatusRequest) (*BinaryStatus, error)
	DownloadBinary(*DownloadBinaryRequest, grpc.ServerStreamingServer[DownloadProgress]) error
	VerifyBinary(context.Context, *VerifyBinaryRequest) (*VerifyBinaryResponse, error)
	mustEmbedUnimplementedNodeServiceServer()
}

// UnimplementedNodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeServiceServer struct{}

func (UnimplementedNodeServiceServer) GetPlatformCapabilities(context.Context, *GetPlatformCapabilitiesRequest) (*PlatformCapabilities, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlatformCapabilities not implemented")
}
func (UnimplementedNodeServiceServer) StartNode(context.Context, *StartNodeRequest) (*NodeStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method StartNode not implemented")
}
func (UnimplementedNodeServiceServer) StopNode(context.Context, *StopNodeRequest) (*NodeStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method StopNode not implemented")
}
func (UnimplementedNodeServiceServer) RestartNode(context.Context, *RestartNodeRequest) (*NodeStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method RestartNode not implemented")
}
func (UnimplementedNodeServiceServer) GetNodeStatus(context.Context, *GetNodeStatusRequest) (*NodeStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNodeStatus not implemented")
}
func (UnimplementedNodeServiceServer) GetAllNodeStatuses(context.Context, *GetAllNodeStatusesRequest) (*AllNodeStatusesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllNodeStatuses not implemented")
}
func (UnimplementedNodeServiceServer) GetSyncProgress(context.Context, *GetSyncProgressRequest) (*SyncProgress, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSyncProgress not implemented")
}
func (UnimplementedNodeServiceServer) WatchNodeStatus(*WatchNodeStatusRequest, grpc.ServerStreamingServer[NodeStatusUpdate]) error {
	return status.Error(codes.Unimplemented, "method WatchNodeStatus not implemented")
}
func (UnimplementedNodeServiceServer) WatchLogs(*WatchLogsRequest, grpc.ServerStreamingServer[LogEntry]) error {
	return status.Error(codes.Unimplemented, "method WatchLogs not implemented")
}
func (UnimplementedNodeServiceServer) CheckBinaryStatus(context.Context, *CheckBinaryStatusRequest) (*BinaryStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckBinaryStatus not implemented")
}
func (UnimplementedNodeServiceServer) DownloadBinary(*DownloadBinaryRequest, grpc.ServerStreamingServer[DownloadProgress]) error {
	return status.Error(codes.Unimplemented, "method DownloadBinary not implemented")
}
func (UnimplementedNodeServiceServer) VerifyBinary(context.Context, *VerifyBinaryRequest) (*VerifyBinaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyBinary not implemented")
}
func (UnimplementedNodeServiceServer) mustEmbedUnimplementedNodeServiceServer() {}
func (UnimplementedNodeServiceServer) testEmbeddedByValue()                     {}

// UnsafeNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeServiceServer will
// result in compilation errors.
type UnsafeNodeServiceServer interface {
	mustEmbedUnimplementedNodeServiceServer()
}

func RegisterNodeServiceServer(s grpc.ServiceRegistrar, srv NodeServiceServer) {
	// If the following call panics, it indicates UnimplementedNodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeService_ServiceDesc, srv)
}

func _NodeService_GetPlatformCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlatformCapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetPlatformCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_GetPlatformCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetPlatformCapabilities(ctx, req.(*GetPlatformCapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_StartNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).StartNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_StartNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).StartNode(ctx, req.(*StartNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_StopNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).StopNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_StopNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).StopNode(ctx, req.(*StopNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_RestartNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestartNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).RestartNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_RestartNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).RestartNode(ctx, req.(*RestartNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_GetNodeStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetNodeStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_GetNodeStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetNodeStatus(ctx, req.(*GetNodeStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_GetAllNodeStatuses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllNodeStatusesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetAllNodeStatuses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_GetAllNodeStatuses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetAllNodeStatuses(ctx, req.(*GetAllNodeStatusesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_GetSyncProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSyncProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetSyncProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_GetSyncProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetSyncProgress(ctx, req.(*GetSyncProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_WatchNodeStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchNodeStatusRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeServiceServer).WatchNodeStatus(m, &grpc.GenericServerStream[WatchNodeStatusRequest, NodeStatusUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_WatchNodeStatusServer = grpc.ServerStreamingServer[NodeStatusUpdate]

func _NodeService_WatchLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeServiceServer).WatchLogs(m, &grpc.GenericServerStream[WatchLogsRequest, LogEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_WatchLogsServer = grpc.ServerStreamingServer[LogEntry]

func _NodeService_CheckBinaryStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckBinaryStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).CheckBinaryStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_CheckBinaryStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).CheckBinaryStatus(ctx, req.(*CheckBinaryStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_DownloadBinary_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadBinaryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeServiceServer).DownloadBinary(m, &grpc.GenericServerStream[DownloadBinaryRequest, DownloadProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_DownloadBinaryServer = grpc.ServerStreamingServer[DownloadProgress]

func _NodeService_VerifyBinary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyBinaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).VerifyBinary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_VerifyBinary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).VerifyBinary(ctx, req.(*VerifyBinaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeService_ServiceDesc is the grpc.ServiceDesc for NodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xswallet.NodeService",
	HandlerType: (*NodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPlatformCapabilities",
			Handler:    _NodeService_GetPlatformCapabilities_Handler,
		},
		{
			MethodName: "StartNode",
			Handler:    _NodeService_StartNode_Handler,
		},
		{
			MethodName: "StopNode",
			Handler:    _NodeService_StopNode_Handler,
		},
		{
			MethodName: "RestartNode",
			Handler:    _NodeService_RestartNode_Handler,
		},
		{
			MethodName: "GetNodeStatus",
			Handler:    _NodeService_GetNodeStatus_Handler,
		},
		{
			MethodName: "GetAllNodeStatuses",
			Handler:    _NodeService_GetAllNodeStatuses_Handler,
		},
		{
			MethodName: "GetSyncProgress",
			Handler:    _NodeService_GetSyncProgress_Handler,
		},
		{
			MethodName: "CheckBinaryStatus",
			Handler:    _NodeService_CheckBinaryStatus_Handler,
		},
		{
			MethodName: "VerifyBinary",
			Handler:    _NodeService_VerifyBinary_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchNodeStatus",
			Handler:       _NodeService_WatchNodeStatus_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchLogs",
			Handler:       _NodeService_WatchLogs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "DownloadBinary",
			Handler:       _NodeService_DownloadBinary_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "node.proto",
}
