// XS Wallet - Swap Service Protocol
// Go Core é autoritativo; TS/RN são apenas clientes

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: swap.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SwapService_QuoteSwap_FullMethodName     = "/xswallet.SwapService/QuoteSwap"
	SwapService_CreateSwap_FullMethodName    = "/xswallet.SwapService/CreateSwap"
	SwapService_LockSwap_FullMethodName      = "/xswallet.SwapService/LockSwap"
	SwapService_CommitSwap_FullMethodName    = "/xswallet.SwapService/CommitSwap"
	SwapService_CancelSwap_FullMethodName    = "/xswallet.SwapService/CancelSwap"
	SwapService_GetSwap_FullMethodName       = "/xswallet.SwapService/GetSwap"
	SwapService_ListSwaps_FullMethodName     = "/xswallet.SwapService/ListSwaps"
	SwapService_GetSwapEvents_FullMethodName = "/xswallet.SwapService/GetSwapEvents"
	SwapService_WatchSwap_FullMethodName     = "/xswallet.SwapService/WatchSwap"
	SwapService_WatchAllSwaps_FullMethodName = "/xswallet.SwapService/WatchAllSwaps"
)

// SwapServiceClient is the client API for SwapService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SwapServiceClient interface {
	// Quote (antes de criar)
	QuoteSwap(ctx context.Context, in *QuoteSwapRequest, opts ...grpc.CallOption) (*SwapQuote, error)
	// Lifecycle
	CreateSwap(ctx context.Context, in *CreateSwapRequest, opts ...grpc.CallOption) (*SwapSnapshot, error)
	LockSwap(ctx context.Context, in *LockSwapRequest, opts ...grpc.CallOption) (*SwapSnapshot, error)
	CommitSwap(ctx context.Context, in *CommitSwapRequest, opts ...grpc.CallOption) (*SwapSnapshot, error)
	CancelSwap(ctx context.Context, in *CancelSwapRequest, opts ...grpc.CallOption) (*SwapSnapshot, error)
	// Queries
	GetSwap(ctx context.Context, in *GetSwapRequest, opts ...grpc.CallOption) (*SwapSnapshot, error)
	ListSwaps(ctx context.Context, in *ListSwapsRequest, opts ...grpc.CallOption) (*ListSwapsResponse, error)
	GetSwapEvents(ctx context.Context, in *GetSwapEventsRequest, opts ...grpc.CallOption) (*GetSwapEventsResponse, error)
	// Streaming - eventos em tempo real (resumable)
	WatchSwap(ctx context.Context, in *WatchSwapRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SwapEvent], error)
	WatchAllSwaps(ctx context.Context, in *WatchAllSwapsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SwapEvent], error)
}

type swapServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSwapServiceClient(cc grpc.ClientConnInterface) SwapServiceClient {
	return &swapServiceClient{cc}
}

func (c *swapServiceClient) QuoteSwap(ctx context.Context, in *QuoteSwapRequest, opts ...grpc.CallOption) (*SwapQuote, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SwapQuote)
	err := c.cc.Invoke(ctx, SwapService_QuoteSwap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swapServiceClient) CreateSwap(ctx context.Context, in *CreateSwapRequest, opts ...grpc.CallOption) (*SwapSnapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SwapSnapshot)
	err := c.cc.Invoke(ctx, SwapService_CreateSwap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swapServiceClient) LockSwap(ctx context.Context, in *LockSwapRequest, opts ...grpc.CallOption) (*SwapSnapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SwapSnapshot)
	err := c.cc.Invoke(ctx, SwapService_LockSwap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swapServiceClient) CommitSwap(ctx context.Context, in *CommitSwapRequest, opts ...grpc.CallOption) (*SwapSnapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SwapSnapshot)
	err := c.cc.Invoke(ctx, SwapService_CommitSwap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swapServiceClient) CancelSwap(ctx context.Context, in *CancelSwapRequest, opts ...grpc.CallOption) (*SwapSnapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SwapSnapshot)
	err := c.cc.Invoke(ctx, SwapService_CancelSwap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swapServiceClient) GetSwap(ctx context.Context, in *GetSwapRequest, opts ...grpc.CallOption) (*SwapSnapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SwapSnapshot)
	err := c.cc.Invoke(ctx, SwapService_GetSwap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swapServiceClient) ListSwaps(ctx context.Context, in *ListSwapsRequest, opts ...grpc.CallOption) (*ListSwapsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSwapsResponse)
	err := c.cc.Invoke(ctx, SwapService_ListSwaps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swapServiceClient) GetSwapEvents(ctx context.Context, in *GetSwapEventsRequest, opts ...grpc.CallOption) (*GetSwapEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSwapEventsResponse)
	err := c.cc.Invoke(ctx, SwapService_GetSwapEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swapServiceClient) WatchSwap(ctx context.Context, in *WatchSwapRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SwapEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SwapService_ServiceDesc.Streams[0], SwapService_WatchSwap_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchSwapRequest, SwapEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SwapService_WatchSwapClient = grpc.ServerStreamingClient[SwapEvent]

func (c *swapServiceClient) WatchAllSwaps(ctx context.Context, in *WatchAllSwapsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SwapEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SwapService_ServiceDesc.Streams[1], SwapService_WatchAllSwaps_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchAllSwapsRequest, SwapEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SwapService_WatchAllSwapsClient = grpc.ServerStreamingClient[SwapEvent]

// SwapServiceServer is the server API for SwapService service.
// All implementations must embed UnimplementedSwapServiceServer
// for forward compatibility.
type SwapServiceServer interface {
	// Quote (antes de criar)
	QuoteSwap(context.Context, *QuoteSwapRequest) (*SwapQuote, error)
	// Lifecycle
	CreateSwap(context.Context, *CreateSwapRequest) (*SwapSnapshot, error)
	LockSwap(context.Context, *LockSwapRequest) (*SwapSnapshot, error)
	CommitSwap(context.Context, *CommitSwapRequest) (*SwapSnapshot, error)
	CancelSwap(context.Context, *CancelSwapRequest) (*SwapSnapshot, error)
	// Queries
	GetSwap(context.Context, *GetSwapRequest) (*SwapSnapshot, error)
	ListSwaps(context.Context, *ListSwapsRequest) (*ListSwapsResponse, error)
	GetSwapEvents(context.Context, *GetSwapEventsRequest) (*GetSwapEventsResponse, error)
	// Streaming - eventos em tempo real (resumable)
	WatchSwap(*WatchSwapRequest, grpc.ServerStreamingServer[SwapEvent]) error
	WatchAllSwaps(*WatchAllSwapsRequest, grpc.ServerStreamingServer[SwapEvent]) error
	mustEmbedUnimplementedSwapServiceServer()
}

// UnimplementedSwapServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSwapServiceServer struct{}

func (UnimplementedSwapServiceServer) QuoteSwap(context.Context, *QuoteSwapRequest) (*SwapQuote, error) {
	return nil, status.Error(codes.Unimplemented, "method QuoteSwap not implemented")
}
func (UnimplementedSwapServiceServer) CreateSwap(context.Context, *CreateSwapRequest) (*SwapSnapshot, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSwap not implemented")
}
func (UnimplementedSwapServiceServer) LockSwap(context.Context, *LockSwapRequest) (*SwapSnapshot, error) {
	return nil, status.Error(codes.Unimplemented, "method LockSwap not implemented")
}
func (UnimplementedSwapServiceServer) CommitSwap(context.Context, *CommitSwapRequest) (*SwapSnapshot, error) {
	return nil, status.Error(codes.Unimplemented, "method CommitSwap not implemented")
}
func (UnimplementedSwapServiceServer) CancelSwap(context.Context, *CancelSwapRequest) (*SwapSnapshot, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelSwap not implemented")
}
func (UnimplementedSwapServiceServer) GetSwap(context.Context, *GetSwapRequest) (*SwapSnapshot, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSwap not implemented")
}
func (UnimplementedSwapServiceServer) ListSwaps(context.Context, *ListSwapsRequest) (*ListSwapsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSwaps not implemented")
}
func (UnimplementedSwapServiceServer) GetSwapEvents(context.Context, *GetSwapEventsRequest) (*GetSwapEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSwapEvents not implemented")
}
func (UnimplementedSwapServiceServer) WatchSwap(*WatchSwapRequest, grpc.ServerStreamingServer[SwapEvent]) error {
	return status.Error(codes.Unimplemented, "method WatchSwap not implemented")
}
func (UnimplementedSwapServiceServer) WatchAllSwaps(*WatchAllSwapsRequest, grpc.ServerStreamingServer[SwapEvent]) error {
	return status.Error(codes.Unimplemented, "method WatchAllSwaps not implemented")
}
func (UnimplementedSwapServiceServer) mustEmbedUnimplementedSwapServiceServer() {}
func (UnimplementedSwapServiceServer) testEmbeddedByValue()                     {}

// UnsafeSwapServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SwapServiceServer will
// result in compilation errors.
type UnsafeSwapServiceServer interface {
	mustEmbedUnimplementedSwapServiceServer()
}

func RegisterSwapServiceServer(s grpc.ServiceRegistrar, srv SwapServiceServer) {
	// If the following call panics, it indicates UnimplementedSwapServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SwapService_ServiceDesc, srv)
}

func _SwapService_QuoteSwap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuoteSwapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwapServiceServer).QuoteSwap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwapService_QuoteSwap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwapServiceServer).QuoteSwap(ctx, req.(*QuoteSwapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwapService_CreateSwap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSwapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwapServiceServer).CreateSwap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwapService_CreateSwap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwapServiceServer).CreateSwap(ctx, req.(*CreateSwapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwapService_LockSwap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockSwapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwapServiceServer).LockSwap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwapService_LockSwap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwapServiceServer).LockSwap(ctx, req.(*LockSwapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwapService_CommitSwap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitSwapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwapServiceServer).CommitSwap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwapService_CommitSwap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwapServiceServer).CommitSwap(ctx, req.(*CommitSwapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwapService_CancelSwap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelSwapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwapServiceServer).CancelSwap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwapService_CancelSwap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwapServiceServer).CancelSwap(ctx, req.(*CancelSwapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwapService_GetSwap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSwapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwapServiceServer).GetSwap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwapService_GetSwap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwapServiceServer).GetSwap(ctx, req.(*GetSwapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwapService_ListSwaps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSwapsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwapServiceServer).ListSwaps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwapService_ListSwaps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwapServiceServer).ListSwaps(ctx, req.(*ListSwapsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwapService_GetSwapEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSwapEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwapServiceServer).GetSwapEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwapService_GetSwapEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwapServiceServer).GetSwapEvents(ctx, req.(*GetSwapEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwapService_WatchSwap_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchSwapRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SwapServiceServer).WatchSwap(m, &grpc.GenericServerStream[WatchSwapRequest, SwapEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SwapService_WatchSwapServer = grpc.ServerStreamingServer[SwapEvent]

func _SwapService_WatchAllSwaps_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchAllSwapsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SwapServiceServer).WatchAllSwaps(m, &grpc.GenericServerStream[WatchAllSwapsRequest, SwapEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SwapService_WatchAllSwapsServer = grpc.ServerStreamingServer[SwapEvent]

// SwapService_ServiceDesc is the grpc.ServiceDesc for SwapService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SwapService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xswallet.SwapService",
	HandlerType: (*SwapServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QuoteSwap",
			Handler:    _SwapService_QuoteSwap_Handler,
		},
		{
			MethodName: "CreateSwap",
			Handler:    _SwapService_CreateSwap_Handler,
		},
		{
			MethodName: "LockSwap",
			Handler:    _SwapService_LockSwap_Handler,
		},
		{
			MethodName: "CommitSwap",
			Handler:    _SwapService_CommitSwap_Handler,
		},
		{
			MethodName: "CancelSwap",
			Handler:    _SwapService_CancelSwap_Handler,
		},
		{
			MethodName: "GetSwap",
			Handler:    _SwapService_GetSwap_Handler,
		},
		{
			MethodName: "ListSwaps",
			Handler:    _SwapService_ListSwaps_Handler,
		},
		{
			MethodName: "GetSwapEvents",
			Handler:    _SwapService_GetSwapEvents_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchSwap",
			Handler:       _SwapService_WatchSwap_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchAllSwaps",
			Handler:       _SwapService_WatchAllSwaps_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "swap.proto",
}
