// XS Wallet - Swap Service Protocol
// Go Core é autoritativo; TS/RN são apenas clientes

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: swap.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SwapKind int32

const (
	SwapKind_SWAP_KIND_UNSPECIFIED SwapKind = 0
	SwapKind_SWAP_KIND_SUBMARINE   SwapKind = 1 // On-chain → Lightning
	SwapKind_SWAP_KIND_REVERSE     SwapKind = 2 // Lightning → On-chain
	SwapKind_SWAP_KIND_CHAIN       SwapKind = 3 // BTC ↔ Liquid
)

// Enum value maps for SwapKind.
var (
	SwapKind_name = map[int32]string{
		0: "SWAP_KIND_UNSPECIFIED",
		1: "SWAP_KIND_SUBMARINE",
		2: "SWAP_KIND_REVERSE",
		3: "SWAP_KIND_CHAIN",
	}
	SwapKind_value = map[string]int32{
		"SWAP_KIND_UNSPECIFIED": 0,
		"SWAP_KIND_SUBMARINE":   1,
		"SWAP_KIND_REVERSE":     2,
		"SWAP_KIND_CHAIN":       3,
	}
)

func (x SwapKind) Enum() *SwapKind {
	p := new(SwapKind)
	*p = x
	return p
}

func (x SwapKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SwapKind) Descriptor() protoreflect.EnumDescriptor {
	return file_swap_proto_enumTypes[0].Descriptor()
}

func (SwapKind) Type() protoreflect.EnumType {
	return &file_swap_proto_enumTypes[0]
}

func (x SwapKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SwapKind.Descriptor instead.
func (SwapKind) EnumDescriptor() ([]byte, []int) {
	return file_swap_proto_rawDescGZIP(), []int{0}
}

type SwapState int32

const (
	SwapState_SWAP_STATE_UNSPECIFIED                SwapState = 0
	SwapState_SWAP_STATE_OPEN                       SwapState = 1  // Quote aceito, não bloqueado
	SwapState_SWAP_STATE_LOCKED                     SwapState = 2  // Parâmetros imutáveis
	SwapState_SWAP_STATE_COMMIT_STARTED             SwapState = 3  // Funding tx broadcast
	SwapState_SWAP_STATE_WAITING                    SwapState = 4  // Aguardando contraparte
	SwapState_SWAP_STATE_WAITING_CLAIM_DETAILS      SwapState = 5  // Aguardando detalhes de claim
	SwapState_SWAP_STATE_SIGNING_MUSIG2_PARTIAL     SwapState = 6  // Criando assinatura parcial
	SwapState_SWAP_STATE_SENT_PARTIAL_TO_PROVIDER   SwapState = 7  // Partial sig enviada
	SwapState_SWAP_STATE_WAITING_PROVIDER_BROADCAST SwapState = 8  // Aguardando broadcast
	SwapState_SWAP_STATE_REFUND_COOP_WAITING        SwapState = 9  // Tentando refund cooperativo
	SwapState_SWAP_STATE_FALLBACK_SCRIPT_READY      SwapState = 10 // Preparando script-path
	SwapState_SWAP_STATE_REFUNDING                  SwapState = 11 // Refund tx broadcast
	SwapState_SWAP_STATE_COMPLETED                  SwapState = 12 // Terminal: sucesso
	SwapState_SWAP_STATE_FAILED                     SwapState = 13 // Terminal: falha
	SwapState_SWAP_STATE_CANCELED                   SwapState = 14 // Terminal: cancelado
)

// Enum value maps for SwapState.
var (
	SwapState_name = map[int32]string{
		0:  "SWAP_STATE_UNSPECIFIED",
		1:  "SWAP_STATE_OPEN",
		2:  "SWAP_STATE_LOCKED",
		3:  "SWAP_STATE_COMMIT_STARTED",
		4:  "SWAP_STATE_WAITING",
		5:  "SWAP_STATE_WAITING_CLAIM_DETAILS",
		6:  "SWAP_STATE_SIGNING_MUSIG2_PARTIAL",
		7:  "SWAP_STATE_SENT_PARTIAL_TO_PROVIDER",
		8:  "SWAP_STATE_WAITING_PROVIDER_BROADCAST",
		9:  "SWAP_STATE_REFUND_COOP_WAITING",
		10: "SWAP_STATE_FALLBACK_SCRIPT_READY",
		11: "SWAP_STATE_REFUNDING",
		12: "SWAP_STATE_COMPLETED",
		13: "SWAP_STATE_FAILED",
		14: "SWAP_STATE_CANCELED",
	}
	SwapState_value = map[string]int32{
		"SWAP_STATE_UNSPECIFIED":                0,
		"SWAP_STATE_OPEN":                       1,
		"SWAP_STATE_LOCKED":                     2,
		"SWAP_STATE_COMMIT_STARTED":             3,
		"SWAP_STATE_WAITING":                    4,
		"SWAP_STATE_WAITING_CLAIM_DETAILS":      5,
		"SWAP_STATE_SIGNING_MUSIG2_PARTIAL":     6,
		"SWAP_STATE_SENT_PARTIAL_TO_PROVIDER":   7,
		"SWAP_STATE_WAITING_PROVIDER_BROADCAST": 8,
		"SWAP_STATE_REFUND_COOP_WAITING":        9,
		"SWAP_STATE_FALLBACK_SCRIPT_READY":      10,
		"SWAP_STATE_REFUNDING":                  11,
		"SWAP_STATE_COMPLETED":                  12,
		"SWAP_STATE_FAILED":                     13,
		"SWAP_STATE_CANCELED":                   14,
	}
)

func (x SwapState) Enum() *SwapState {
	p := new(SwapState)
	*p = x
	return p
}

func (x SwapState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SwapState) Descriptor() protoreflect.EnumDescriptor {
	return file_swap_proto_enumTypes[1].Descriptor()
}

func (SwapState) Type() protoreflect.EnumType {
	return &file_swap_proto_enumTypes[1]
}

func (x SwapState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SwapState.Descriptor instead.
func (SwapState) EnumDescriptor() ([]byte, []int) {
	return file_swap_proto_rawDescGZIP(), []int{1}
}

type QuoteSwapRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Kind      SwapKind               `protobuf:"varint,1,opt,name=kind,proto3,enum=xswallet.SwapKind" json:"kind,omitempty"`
	FromChain Chain                  `protobuf:"varint,2,opt,name=from_chain,json=fromChain,proto3,enum=xswallet.Chain" json:"from_chain,omitempty"`
	ToChain   Chain                  `protobuf:"varint,3,opt,name=to_chain,json=toChain,proto3,enum=xswallet.Chain" json:"to_chain,omitempty"`
	AmountSat uint64                 `protobuf:"varint,4,opt,name=amount_sat,json=amountSat,proto3" json:"amount_sat,omitempty"`
	// Types that are valid to be assigned to Params:
	//
	//	*QuoteSwapRequest_Submarine
	//	*QuoteSwapRequest_Reverse
	//	*QuoteSwapRequest_Chain
	Params        isQuoteSwapRequest_Params `protobuf_oneof:"params"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuoteSwapRequest) Reset() {
	*x = QuoteSwapRequest{}
	mi := &file_swap_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteSwapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteSwapRequest) ProtoMessage() {}

func (x *QuoteSwapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swap_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteSwapRequest.ProtoReflect.Descriptor instead.
func (*QuoteSwapRequest) Descriptor() ([]byte, []int) {
	return file_swap_proto_rawDescGZIP(), []int{0}
}

func (x *QuoteSwapRequest) GetKind() SwapKind {
	if x != nil {
		return x.Kind
	}
	return SwapKind_SWAP_KIND_UNSPECIFIED
}

func (x *QuoteSwapRequest) GetFromChain() Chain {
	if x != nil {
		return x.FromChain
	}
	return Chain_CHAIN_UNSPECIFIED
}

func (x *QuoteSwapRequest) GetToChain() Chain {
	if x != nil {
		return x.ToChain
	}
	return Chain_CHAIN_UNSPECIFIED
}

func (x *QuoteSwapRequest) GetAmountSat() uint64 {
	if x != nil {
		return x.AmountSat
	}
	return 0
}

func (x *QuoteSwapRequest) GetParams() isQuoteSwapRequest_Params {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *QuoteSwapRequest) GetSubmarine() *SubmarineQuoteParams {
	if x != nil {
		if x, ok := x.Params.(*QuoteSwapRequest_Submarine); ok {
			return x.Submarine
		}
	}
	return nil
}

func (x *QuoteSwapRequest) GetReverse() *ReverseQuoteParams {
	if x != nil {
		if x, ok := x.Params.(*QuoteSwapRequest_Reverse); ok {
			return x.Reverse
		}
	}
	return nil
}

func (x *QuoteSwapRequest) GetChain() *ChainQuoteParams {
	if x != nil {
		if x, ok := x.Params.(*QuoteSwapRequest_Chain); ok {
			return x.Chain
		}
	}
	return nil
}

type isQuoteSwapRequest_Params interface {
	isQuoteSwapRequest_Params()
}

type QuoteSwapRequest_Submarine struct {
	Submarine *SubmarineQuoteParams `protobuf:"bytes,10,opt,name=submarine,proto3,oneof"`
}

type QuoteSwapRequest_Reverse struct {
	Reverse *ReverseQuoteParams `protobuf:"bytes,11,opt,name=reverse,proto3,oneof"`
}

type QuoteSwapRequest_Chain struct {
	Chain *ChainQuoteParams `protobuf:"bytes,12,opt,name=chain,proto3,oneof"`
}

func (*QuoteSwapRequest_Submarine) isQuoteSwapRequest_Params() {}

func (*QuoteSwapRequest_Reverse) isQuoteSwapRequest_Params() {}

func (*QuoteSwapRequest_Chain) isQuoteSwapRequest_Params() {}

type SubmarineQuoteParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invoice       string                 `protobuf:"bytes,1,opt,name=invoice,proto3" json:"invoice,omitempty"` // Invoice LN do usuário
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmarineQuoteParams) Reset() {
	*x = SubmarineQuoteParams{}
	mi := &file_swap_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmarineQuoteParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmarineQuoteParams) ProtoMessage() {}

func (x *SubmarineQuoteParams) ProtoReflect() protoreflect.Message {
	mi := &file_swap_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmarineQuoteParams.ProtoReflect.Descriptor instead.
func (*SubmarineQuoteParams) Descriptor() ([]byte, []int) {
	return file_swap_proto_rawDescGZIP(), []int{1}
}

func (x *SubmarineQuoteParams) GetInvoice() string {
	if x != nil {
		return x.Invoice
	}
	return ""
}

type ReverseQuoteParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PayoutAddress string                 `protobuf:"bytes,1,opt,name=payout_address,json=payoutAddress,proto3" json:"payout_address,omitempty"` // Endereço BTC/Liquid para receber
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReverseQuoteParams) Reset() {
	*x = ReverseQuoteParams{}
	mi := &file_swap_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReverseQuoteParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReverseQuoteParams) ProtoMessage() {}

func (x *ReverseQuoteParams) ProtoReflect() protoreflect.Message {
	mi := &file_swap_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReverseQuoteParams.ProtoReflect.Descriptor instead.
func (*ReverseQuoteParams) Descriptor() ([]byte, []int) {
	return file_swap_proto_rawDescGZIP(), []int{2}
}

func (x *ReverseQuoteParams) GetPayoutAddress() string {
	if x != nil {
		return x.PayoutAddress
	}
	return ""
}

type ChainQuoteParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PayoutAddress string                 `protobuf:"bytes,1,opt,name=payout_address,json=payoutAddress,proto3" json:"payout_address,omitempty"` // Endereço na chain de destino
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChainQuoteParams) Reset() {
	*x = ChainQuoteParams{}
	mi := &file_swap_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainQuoteParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainQuoteParams) ProtoMessage() {}

func (x *ChainQuoteParams) ProtoReflect() protoreflect.Message {
	mi := &file_swap_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainQuoteParams.ProtoReflect.Descriptor instead.
func (*ChainQuoteParams) Descriptor() ([]byte, []int) {
	return file_swap_proto_rawDescGZIP(), []int{3}
}

func (x *ChainQuoteParams) GetPayoutAddress() string {
	if x != nil {
		return x.PayoutAddress
	}
	return ""
}

type SwapQuote struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	QuoteId   string                 `protobuf:"bytes,1,opt,name=quote_id,json=quoteId,proto3" json:"quote_id,omitempty"` // ID do quote (válido por X minutos)
	Kind      SwapKind               `protobuf:"varint,2,opt,name=kind,proto3,enum=xswallet.SwapKind" json:"kind,omitempty"`
	FromChain Chain                  `protobuf:"varint,3,opt,name=from_chain,json=fromChain,proto3,enum=xswallet.Chain" json:"from_chain,omitempty"`
	ToChain   Chain                  `protobuf:"varint,4,opt,name=to_chain,json=toChain,proto3,enum=xswallet.Chain" json:"to_chain,omitempty"`
	AmountSat uint64                 `protobuf:"varint,5,opt,name=amount_sat,json=amountSat,proto3" json:"amount_sat,omitempty"`
	// Fees
	ProviderFeeSat uint64  `protobuf:"varint,10,opt,name=provider_fee_sat,json=providerFeeSat,proto3" json:"provider_fee_sat,omitempty"`
	NetworkFeeSat  uint64  `protobuf:"varint,11,opt,name=network_fee_sat,json=networkFeeSat,proto3" json:"network_fee_sat,omitempty"`
	TotalFeeSat    uint64  `protobuf:"varint,12,opt,name=total_fee_sat,json=totalFeeSat,proto3" json:"total_fee_sat,omitempty"`
	FeePercentage  float64 `protobuf:"fixed64,13,opt,name=fee_percentage,json=feePercentage,proto3" json:"fee_percentage,omitempty"`
	// Provider data
	LockupAddress string `protobuf:"bytes,20,opt,name=lockup_address,json=lockupAddress,proto3" json:"lockup_address,omitempty"`
	ClaimAddress  string `protobuf:"bytes,21,opt,name=claim_address,json=claimAddress,proto3" json:"claim_address,omitempty"`
	// Timeouts
	UserTimeoutBlocks     uint32 `protobuf:"varint,30,opt,name=user_timeout_blocks,json=userTimeoutBlocks,proto3" json:"user_timeout_blocks,omitempty"`
	ProviderTimeoutBlocks uint32 `protobuf:"varint,31,opt,name=provider_timeout_blocks,json=providerTimeoutBlocks,proto3" json:"provider_timeout_blocks,omitempty"`
	// Validade do quote
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,40,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwapQuote) Reset() {
	*x = SwapQuote{}
	mi := &file_swap_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwapQuote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwapQuote) ProtoMessage() {}

func (x *SwapQuote) ProtoReflect() protoreflect.Message {
	mi := &file_swap_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwapQuote.ProtoReflect.Descriptor instead.
func (*SwapQuote) Descriptor() ([]byte, []int) {
	return file_swap_proto_rawDescGZIP(), []int{4}
}

func (x *SwapQuote) GetQuoteId() string {
	if x != nil {
		return x.QuoteId
	}
	return ""
}

func (x *SwapQuote) GetKind() SwapKind {
	if x != nil {
		return x.Kind
	}
	return SwapKind_SWAP_KIND_UNSPECIFIED
}

func (x *SwapQuote) GetFromChain() Chain {
	if x != nil {
		return x.FromChain
	}
	return Chain_CHAIN_UNSPECIFIED
}

func (x *SwapQuote) GetToChain() Chain {
	if x != nil {
		return x.ToChain
	}
	return Chain_CHAIN_UNSPECIFIED
}

func (x *SwapQuote) GetAmountSat() uint64 {
	if x != nil {
		return x.AmountSat
	}
	return 0
}

func (x *SwapQuote) GetProviderFeeSat() uint64 {
	if x != nil {
		return x.ProviderFeeSat
	}
	return 0
}

func (x *SwapQuote) GetNetworkFeeSat() uint64 {
	if x != nil {
		return x.NetworkFeeSat
	}
	return 0
}

func (x *SwapQuote) GetTotalFeeSat() uint64 {
	if x != nil {
		return x.TotalFeeSat
	}
	return 0
}

func (x *SwapQuote) GetFeePercentage() float64 {
	if x != nil {
		return x.FeePercentage
	}
	return 0
}

func (x *SwapQuote) GetLockupAddress() string {
	if x != nil {
		return x.LockupAddress
	}
	return ""
}

func (x *SwapQuote) GetClaimAddress() string {
	if x != nil {
		return x.ClaimAddress
	}
	return ""
}

func (x *SwapQuote) GetUserTimeoutBlocks() uint32 {
	if x != nil {
		return x.UserTimeoutBlocks
	}
	return 0
}

func (x *SwapQuote) GetProviderTimeoutBlocks() uint32 {
	if x != nil {
		return x.ProviderTimeoutBlocks
	}
	return 0
}

func (x *SwapQuote) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type CreateSwapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuoteId       string                 `protobuf:"bytes,1,opt,name=quote_id,json=quoteId,proto3" json:"quote_id,omitempty"` // Quote aceito
	FeePolicy     *FeePolicy             `protobuf:"bytes,2,opt,name=fee_policy,json=feePolicy,proto3" json:"fee_policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSwapRequest) Reset() {
	*x = CreateSwapRequest{}
	mi := &file_swap_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSwapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSwapRequest) ProtoMessage() {}

func (x *CreateSwapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swap_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSwapRequest.ProtoReflect.Descriptor instead.
func (*CreateSwapRequest) Descriptor() ([]byte, []int) {
	return file_swap_proto_rawDescGZIP(), []int{5}
}

func (x *CreateSwapRequest) GetQuoteId() string {
	if x != nil {
		return x.QuoteId
	}
	return ""
}

func (x *CreateSwapRequest) GetFeePolicy() *FeePolicy {
	if x != nil {
		return x.FeePolicy
	}
	return nil
}

type LockSwapRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SwapId          string                 `protobuf:"bytes,1,opt,name=swap_id,json=swapId,proto3" json:"swap_id,omitempty"`
	ExpectedVersion uint64                 `protobuf:"varint,2,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"` // CAS: versão esperada
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LockSwapRequest) Reset() {
	*x = LockSwapRequest{}
	mi := &file_swap_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockSwapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockSwapRequest) ProtoMessage() {}

func (x *LockSwapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swap_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockSwapRequest.ProtoReflect.Descriptor instead.
func (*LockSwapRequest) Descriptor() ([]byte, []int) {
	return file_swap_proto_rawDescGZIP(), []int{6}
}

func (x *LockSwapRequest) GetSwapId() string {
	if x != nil {
		return x.SwapId
	}
	return ""
}

func (x *LockSwapRequest) GetExpectedVersion() uint64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

type CommitSwapRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SwapId          string                 `protobuf:"bytes,1,opt,name=swap_id,json=swapId,proto3" json:"swap_id,omitempty"`
	ExpectedVersion uint64                 `protobuf:"varint,2,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CommitSwapRequest) Reset() {
	*x = CommitSwapRequest{}
	mi := &file_swap_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitSwapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitSwapRequest) ProtoMessage() {}

func (x *CommitSwapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swap_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitSwapRequest.ProtoReflect.Descriptor instead.
func (*CommitSwapRequest) Descriptor() ([]byte, []int) {
	return file_swap_proto_rawDescGZIP(), []int{7}
}

func (x *CommitSwapRequest) GetSwapId() string {
	if x != nil {
		return x.SwapId
	}
	return ""
}

func (x *CommitSwapRequest) GetExpectedVersion() uint64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

type CancelSwapRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SwapId          string                 `protobuf:"bytes,1,opt,name=swap_id,json=swapId,proto3" json:"swap_id,omitempty"`
	ExpectedVersion uint64                 `protobuf:"varint,2,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	Reason          string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CancelSwapRequest) Reset() {
	*x = CancelSwapRequest{}
	mi := &file_swap_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelSwapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelSwapRequest) ProtoMessage() {}

func (x *CancelSwapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swap_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelSwapRequest.ProtoReflect.Descriptor instead.
func (*CancelSwapRequest) Descriptor() ([]byte, []int) {
	return file_swap_proto_rawDescGZIP(), []int{8}
}

func (x *CancelSwapRequest) GetSwapId() string {
	if x != nil {
		return x.SwapId
	}
	return ""
}

func (x *CancelSwapRequest) GetExpectedVersion() uint64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

func (x *CancelSwapRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type GetSwapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SwapId        string                 `protobuf:"bytes,1,opt,name=swap_id,json=swapId,proto3" json:"swap_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSwapRequest) Reset() {
	*x = GetSwapRequest{}
	mi := &file_swap_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSwapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSwapRequest) ProtoMessage() {}

func (x *GetSwapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swap_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSwapRequest.ProtoReflect.Descriptor instead.
func (*GetSwapRequest) Descriptor() ([]byte, []int) {
	return file_swap_proto_rawDescGZIP(), []int{9}
}

func (x *GetSwapRequest) GetSwapId() string {
	if x != nil {
		return x.SwapId
	}
	return ""
}

type ListSwapsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilterState   SwapState              `protobuf:"varint,1,opt,name=filter_state,json=filterState,proto3,enum=xswallet.SwapState" json:"filter_state,omitempty"` // Opcional: filtrar por estado
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSwapsRequest) Reset() {
	*x = ListSwapsRequest{}
	mi := &file_swap_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSwapsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSwapsRequest) ProtoMessage() {}

func (x *ListSwapsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swap_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSwapsRequest.ProtoReflect.Descriptor instead.
func (*ListSwapsRequest) Descriptor() ([]byte, []int) {
	return file_swap_proto_rawDescGZIP(), []int{10}
}

func (x *ListSwapsRequest) GetFilterState() SwapState {
	if x != nil {
		return x.FilterState
	}
	return SwapState_SWAP_STATE_UNSPECIFIED
}

func (x *ListSwapsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListSwapsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetSwapEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SwapId        string                 `protobuf:"bytes,1,opt,name=swap_id,json=swapId,proto3" json:"swap_id,omitempty"`
	AfterSeq      uint64                 `protobuf:"varint,2,opt,name=after_seq,json=afterSeq,proto3" json:"after_seq,omitempty"` // Eventos após esta sequência
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSwapEventsRequest) Reset() {
	*x = GetSwapEventsRequest{}
	mi := &file_swap_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSwapEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSwapEventsRequest) ProtoMessage() {}

func (x *GetSwapEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swap_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSwapEventsRequest.ProtoReflect.Descriptor instead.
func (*GetSwapEventsRequest) Descriptor() ([]byte, []int) {
	return file_swap_proto_rawDescGZIP(), []int{11}
}

func (x *GetSwapEventsRequest) GetSwapId() string {
	if x != nil {
		return x.SwapId
	}
	return ""
}

func (x *GetSwapEventsRequest) GetAfterSeq() uint64 {
	if x != nil {
		return x.AfterSeq
	}
	return 0
}

type WatchSwapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SwapId        string                 `protobuf:"bytes,1,opt,name=swap_id,json=swapId,proto3" json:"swap_id,omitempty"`
	FromSeq       uint64                 `protobuf:"varint,2,opt,name=from_seq,json=fromSeq,proto3" json:"from_seq,omitempty"` // Resumable: começar desta sequência
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchSwapRequest) Reset() {
	*x = WatchSwapRequest{}
	mi := &file_swap_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchSwapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchSwapRequest) ProtoMessage() {}

func (x *WatchSwapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swap_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchSwapRequest.ProtoReflect.Descriptor instead.
func (*WatchSwapRequest) Descriptor() ([]byte, []int) {
	return file_swap_proto_rawDescGZIP(), []int{12}
}

func (x *WatchSwapRequest) GetSwapId() string {
	if x != nil {
		return x.SwapId
	}
	return ""
}

func (x *WatchSwapRequest) GetFromSeq() uint64 {
	if x != nil {
		return x.FromSeq
	}
	return 0
}

type WatchAllSwapsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilterStates  []SwapState            `protobuf:"varint,1,rep,packed,name=filter_states,json=filterStates,proto3,enum=xswallet.SwapState" json:"filter_states,omitempty"`
	FromSeq       uint64                 `protobuf:"varint,2,opt,name=from_seq,json=fromSeq,proto3" json:"from_seq,omitempty"` // Resumable: começar desta sequência
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchAllSwapsRequest) Reset() {
	*x = WatchAllSwapsRequest{}
	mi := &file_swap_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchAllSwapsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchAllSwapsRequest) ProtoMessage() {}

func (x *WatchAllSwapsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swap_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchAllSwapsRequest.ProtoReflect.Descriptor instead.
func (*WatchAllSwapsRequest) Descriptor() ([]byte, []int) {
	return file_swap_proto_rawDescGZIP(), []int{13}
}

func (x *WatchAllSwapsRequest) GetFilterStates() []SwapState {
	if x != nil {
		return x.FilterStates
	}
	return nil
}

func (x *WatchAllSwapsRequest) GetFromSeq() uint64 {
	if x != nil {
		return x.FromSeq
	}
	return 0
}

type SwapSnapshot struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Id      string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind    SwapKind               `protobuf:"varint,2,opt,name=kind,proto3,enum=xswallet.SwapKind" json:"kind,omitempty"`
	State   SwapState              `protobuf:"varint,3,opt,name=state,proto3,enum=xswallet.SwapState" json:"state,omitempty"`
	Version uint64                 `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"` // Para CAS
	Network Network                `protobuf:"varint,5,opt,name=network,proto3,enum=xswallet.Network" json:"network,omitempty"`
	// Intent (imutável após lock)
	LockedIntent *LockedIntent `protobuf:"bytes,10,opt,name=locked_intent,json=lockedIntent,proto3" json:"locked_intent,omitempty"`
	// Chaves e scripts (APENAS PÚBLICAS)
	SwapKeyIndex    uint32 `protobuf:"varint,20,opt,name=swap_key_index,json=swapKeyIndex,proto3" json:"swap_key_index,omitempty"`
	PreimageHashHex string `protobuf:"bytes,21,opt,name=preimage_hash_hex,json=preimageHashHex,proto3" json:"preimage_hash_hex,omitempty"` // H = SHA256(R), R nunca exposto
	ClaimPubkeyHex  string `protobuf:"bytes,22,opt,name=claim_pubkey_hex,json=claimPubkeyHex,proto3" json:"claim_pubkey_hex,omitempty"`
	RefundPubkeyHex string `protobuf:"bytes,23,opt,name=refund_pubkey_hex,json=refundPubkeyHex,proto3" json:"refund_pubkey_hex,omitempty"`
	// MuSig2 session (APENAS DADOS PÚBLICOS)
	MusigSessionId string `protobuf:"bytes,30,opt,name=musig_session_id,json=musigSessionId,proto3" json:"musig_session_id,omitempty"`
	MusigPubnonce  []byte `protobuf:"bytes,31,opt,name=musig_pubnonce,json=musigPubnonce,proto3" json:"musig_pubnonce,omitempty"` // Public nonce (ok expor)
	// Transações
	LockupTxid      string `protobuf:"bytes,40,opt,name=lockup_txid,json=lockupTxid,proto3" json:"lockup_txid,omitempty"`
	LockupAmountSat uint64 `protobuf:"varint,41,opt,name=lockup_amount_sat,json=lockupAmountSat,proto3" json:"lockup_amount_sat,omitempty"`
	ClaimTxid       string `protobuf:"bytes,42,opt,name=claim_txid,json=claimTxid,proto3" json:"claim_txid,omitempty"`
	RefundTxid      string `protobuf:"bytes,43,opt,name=refund_txid,json=refundTxid,proto3" json:"refund_txid,omitempty"`
	// Timeouts
	TimeoutBlockHeight uint32 `protobuf:"varint,50,opt,name=timeout_block_height,json=timeoutBlockHeight,proto3" json:"timeout_block_height,omitempty"`
	CurrentBlockHeight uint32 `protobuf:"varint,51,opt,name=current_block_height,json=currentBlockHeight,proto3" json:"current_block_height,omitempty"`
	BlocksRemaining    int32  `protobuf:"varint,52,opt,name=blocks_remaining,json=blocksRemaining,proto3" json:"blocks_remaining,omitempty"`
	// Timestamps
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,60,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,61,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Erro (se failed)
	ErrorMessage  string `protobuf:"bytes,70,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwapSnapshot) Reset() {
	*x = SwapSnapshot{}
	mi := &file_swap_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwapSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwapSnapshot) ProtoMessage() {}

func (x *SwapSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_swap_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwapSnapshot.ProtoReflect.Descriptor instead.
func (*SwapSnapshot) Descriptor() ([]byte, []int) {
	return file_swap_proto_rawDescGZIP(), []int{14}
}

func (x *SwapSnapshot) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SwapSnapshot) GetKind() SwapKind {
	if x != nil {
		return x.Kind
	}
	return SwapKind_SWAP_KIND_UNSPECIFIED
}

func (x *SwapSnapshot) GetState() SwapState {
	if x != nil {
		return x.State
	}
	return SwapState_SWAP_STATE_UNSPECIFIED
}

func (x *SwapSnapshot) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SwapSnapshot) GetNetwork() Network {
	if x != nil {
		return x.Network
	}
	return Network_NETWORK_UNSPECIFIED
}

func (x *SwapSnapshot) GetLockedIntent() *LockedIntent {
	if x != nil {
		return x.LockedIntent
	}
	return nil
}

func (x *SwapSnapshot) GetSwapKeyIndex() uint32 {
	if x != nil {
		return x.SwapKeyIndex
	}
	return 0
}

func (x *SwapSnapshot) GetPreimageHashHex() string {
	if x != nil {
		return x.PreimageHashHex
	}
	return ""
}

func (x *SwapSnapshot) GetClaimPubkeyHex() string {
	if x != nil {
		return x.ClaimPubkeyHex
	}
	return ""
}

func (x *SwapSnapshot) GetRefundPubkeyHex() string {
	if x != nil {
		return x.RefundPubkeyHex
	}
	return ""
}

func (x *SwapSnapshot) GetMusigSessionId() string {
	if x != nil {
		return x.MusigSessionId
	}
	return ""
}

func (x *SwapSnapshot) GetMusigPubnonce() []byte {
	if x != nil {
		return x.MusigPubnonce
	}
	return nil
}

func (x *SwapSnapshot) GetLockupTxid() string {
	if x != nil {
		return x.LockupTxid
	}
	return ""
}

func (x *SwapSnapshot) GetLockupAmountSat() uint64 {
	if x != nil {
		return x.LockupAmountSat
	}
	return 0
}

func (x *SwapSnapshot) GetClaimTxid() string {
	if x != nil {
		return x.ClaimTxid
	}
	return ""
}

func (x *SwapSnapshot) GetRefundTxid() string {
	if x != nil {
		return x.RefundTxid
	}
	return ""
}

func (x *SwapSnapshot) GetTimeoutBlockHeight() uint32 {
	if x != nil {
		return x.TimeoutBlockHeight
	}
	return 0
}

func (x *SwapSnapshot) GetCurrentBlockHeight() uint32 {
	if x != nil {
		return x.CurrentBlockHeight
	}
	return 0
}

func (x *SwapSnapshot) GetBlocksRemaining() int32 {
	if x != nil {
		return x.BlocksRemaining
	}
	return 0
}

func (x *SwapSnapshot) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SwapSnapshot) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *SwapSnapshot) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type LockedIntent struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Kind      SwapKind               `protobuf:"varint,1,opt,name=kind,proto3,enum=xswallet.SwapKind" json:"kind,omitempty"`
	FromChain Chain                  `protobuf:"varint,2,opt,name=from_chain,json=fromChain,proto3,enum=xswallet.Chain" json:"from_chain,omitempty"`
	ToChain   Chain                  `protobuf:"varint,3,opt,name=to_chain,json=toChain,proto3,enum=xswallet.Chain" json:"to_chain,omitempty"`
	AmountSat uint64                 `protobuf:"varint,4,opt,name=amount_sat,json=amountSat,proto3" json:"amount_sat,omitempty"`
	Invoice   string                 `protobuf:"bytes,5,opt,name=invoice,proto3" json:"invoice,omitempty"`
	// Fees snapshot
	ProviderFeeSat uint64  `protobuf:"varint,10,opt,name=provider_fee_sat,json=providerFeeSat,proto3" json:"provider_fee_sat,omitempty"`
	NetworkFeeSat  uint64  `protobuf:"varint,11,opt,name=network_fee_sat,json=networkFeeSat,proto3" json:"network_fee_sat,omitempty"`
	TotalFeeSat    uint64  `protobuf:"varint,12,opt,name=total_fee_sat,json=totalFeeSat,proto3" json:"total_fee_sat,omitempty"`
	FeePercentage  float64 `protobuf:"fixed64,13,opt,name=fee_percentage,json=feePercentage,proto3" json:"fee_percentage,omitempty"`
	// Provider quote
	ProviderQuoteId string `protobuf:"bytes,20,opt,name=provider_quote_id,json=providerQuoteId,proto3" json:"provider_quote_id,omitempty"`
	LockupAddress   string `protobuf:"bytes,21,opt,name=lockup_address,json=lockupAddress,proto3" json:"lockup_address,omitempty"`
	ClaimAddress    string `protobuf:"bytes,22,opt,name=claim_address,json=claimAddress,proto3" json:"claim_address,omitempty"`
	// Timeouts acordados
	UserTimeout     uint32 `protobuf:"varint,30,opt,name=user_timeout,json=userTimeout,proto3" json:"user_timeout,omitempty"`
	ProviderTimeout uint32 `protobuf:"varint,31,opt,name=provider_timeout,json=providerTimeout,proto3" json:"provider_timeout,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LockedIntent) Reset() {
	*x = LockedIntent{}
	mi := &file_swap_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockedIntent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockedIntent) ProtoMessage() {}

func (x *LockedIntent) ProtoReflect() protoreflect.Message {
	mi := &file_swap_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockedIntent.ProtoReflect.Descriptor instead.
func (*LockedIntent) Descriptor() ([]byte, []int) {
	return file_swap_proto_rawDescGZIP(), []int{15}
}

func (x *LockedIntent) GetKind() SwapKind {
	if x != nil {
		return x.Kind
	}
	return SwapKind_SWAP_KIND_UNSPECIFIED
}

func (x *LockedIntent) GetFromChain() Chain {
	if x != nil {
		return x.FromChain
	}
	return Chain_CHAIN_UNSPECIFIED
}

func (x *LockedIntent) GetToChain() Chain {
	if x != nil {
		return x.ToChain
	}
	return Chain_CHAIN_UNSPECIFIED
}

func (x *LockedIntent) GetAmountSat() uint64 {
	if x != nil {
		return x.AmountSat
	}
	return 0
}

func (x *LockedIntent) GetInvoice() string {
	if x != nil {
		return x.Invoice
	}
	return ""
}

func (x *LockedIntent) GetProviderFeeSat() uint64 {
	if x != nil {
		return x.ProviderFeeSat
	}
	return 0
}

func (x *LockedIntent) GetNetworkFeeSat() uint64 {
	if x != nil {
		return x.NetworkFeeSat
	}
	return 0
}

func (x *LockedIntent) GetTotalFeeSat() uint64 {
	if x != nil {
		return x.TotalFeeSat
	}
	return 0
}

func (x *LockedIntent) GetFeePercentage() float64 {
	if x != nil {
		return x.FeePercentage
	}
	return 0
}

func (x *LockedIntent) GetProviderQuoteId() string {
	if x != nil {
		return x.ProviderQuoteId
	}
	return ""
}

func (x *LockedIntent) GetLockupAddress() string {
	if x != nil {
		return x.LockupAddress
	}
	return ""
}

func (x *LockedIntent) GetClaimAddress() string {
	if x != nil {
		return x.ClaimAddress
	}
	return ""
}

func (x *LockedIntent) GetUserTimeout() uint32 {
	if x != nil {
		return x.UserTimeout
	}
	return 0
}

func (x *LockedIntent) GetProviderTimeout() uint32 {
	if x != nil {
		return x.ProviderTimeout
	}
	return 0
}

type SwapEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"` // Sequência global (autoincrement)
	SwapId        string                 `protobuf:"bytes,2,opt,name=swap_id,json=swapId,proto3" json:"swap_id,omitempty"`
	FromState     SwapState              `protobuf:"varint,3,opt,name=from_state,json=fromState,proto3,enum=xswallet.SwapState" json:"from_state,omitempty"`
	ToState       SwapState              `protobuf:"varint,4,opt,name=to_state,json=toState,proto3,enum=xswallet.SwapState" json:"to_state,omitempty"`
	Trigger       string                 `protobuf:"bytes,5,opt,name=trigger,proto3" json:"trigger,omitempty"`                            // O que causou a transição
	DetailsJson   string                 `protobuf:"bytes,6,opt,name=details_json,json=detailsJson,proto3" json:"details_json,omitempty"` // Payload adicional
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwapEvent) Reset() {
	*x = SwapEvent{}
	mi := &file_swap_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwapEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwapEvent) ProtoMessage() {}

func (x *SwapEvent) ProtoReflect() protoreflect.Message {
	mi := &file_swap_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwapEvent.ProtoReflect.Descriptor instead.
func (*SwapEvent) Descriptor() ([]byte, []int) {
	return file_swap_proto_rawDescGZIP(), []int{16}
}

func (x *SwapEvent) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *SwapEvent) GetSwapId() string {
	if x != nil {
		return x.SwapId
	}
	return ""
}

func (x *SwapEvent) GetFromState() SwapState {
	if x != nil {
		return x.FromState
	}
	return SwapState_SWAP_STATE_UNSPECIFIED
}

func (x *SwapEvent) GetToState() SwapState {
	if x != nil {
		return x.ToState
	}
	return SwapState_SWAP_STATE_UNSPECIFIED
}

func (x *SwapEvent) GetTrigger() string {
	if x != nil {
		return x.Trigger
	}
	return ""
}

func (x *SwapEvent) GetDetailsJson() string {
	if x != nil {
		return x.DetailsJson
	}
	return ""
}

func (x *SwapEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type ListSwapsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Swaps         []*SwapSnapshot        `protobuf:"bytes,1,rep,name=swaps,proto3" json:"swaps,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSwapsResponse) Reset() {
	*x = ListSwapsResponse{}
	mi := &file_swap_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSwapsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSwapsResponse) ProtoMessage() {}

func (x *ListSwapsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swap_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSwapsResponse.ProtoReflect.Descriptor instead.
func (*ListSwapsResponse) Descriptor() ([]byte, []int) {
	return file_swap_proto_rawDescGZIP(), []int{17}
}

func (x *ListSwapsResponse) GetSwaps() []*SwapSnapshot {
	if x != nil {
		return x.Swaps
	}
	return nil
}

func (x *ListSwapsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetSwapEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*SwapEvent           `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSwapEventsResponse) Reset() {
	*x = GetSwapEventsResponse{}
	mi := &file_swap_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSwapEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSwapEventsResponse) ProtoMessage() {}

func (x *GetSwapEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swap_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSwapEventsResponse.ProtoReflect.Descriptor instead.
func (*GetSwapEventsResponse) Descriptor() ([]byte, []int) {
	return file_swap_proto_rawDescGZIP(), []int{18}
}

func (x *GetSwapEventsResponse) GetEvents() []*SwapEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_swap_proto protoreflect.FileDescriptor

const file_swap_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"swap.proto\x12\bxswallet\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\fcommon.proto\"\xed\x02\n" +
	"\x10QuoteSwapRequest\x12&\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x12.xswallet.SwapKindR\x04kind\x12.\n" +
	"\n" +
	"from_chain\x18\x02 \x01(\x0e2\x0f.xswallet.ChainR\tfromChain\x12*\n" +
	"\bto_chain\x18\x03 \x01(\x0e2\x0f.xswallet.ChainR\atoChain\x12\x1d\n" +
	"\n" +
	"amount_sat\x18\x04 \x01(\x04R\tamountSat\x12>\n" +
	"\tsubmarine\x18\n" +
	" \x01(\v2\x1e.xswallet.SubmarineQuoteParamsH\x00R\tsubmarine\x128\n" +
	"\areverse\x18\v \x01(\v2\x1c.xswallet.ReverseQuoteParamsH\x00R\areverse\x122\n" +
	"\x05chain\x18\f \x01(\v2\x1a.xswallet.ChainQuoteParamsH\x00R\x05chainB\b\n" +
	"\x06params\"0\n" +
	"\x14SubmarineQuoteParams\x12\x18\n" +
	"\ainvoice\x18\x01 \x01(\tR\ainvoice\";\n" +
	"\x12ReverseQuoteParams\x12%\n" +
	"\x0epayout_address\x18\x01 \x01(\tR\rpayoutAddress\"9\n" +
	"\x10ChainQuoteParams\x12%\n" +
	"\x0epayout_address\x18\x01 \x01(\tR\rpayoutAddress\"\xd5\x04\n" +
	"\tSwapQuote\x12\x19\n" +
	"\bquote_id\x18\x01 \x01(\tR\aquoteId\x12&\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x12.xswallet.SwapKindR\x04kind\x12.\n" +
	"\n" +
	"from_chain\x18\x03 \x01(\x0e2\x0f.xswallet.ChainR\tfromChain\x12*\n" +
	"\bto_chain\x18\x04 \x01(\x0e2\x0f.xswallet.ChainR\atoChain\x12\x1d\n" +
	"\n" +
	"amount_sat\x18\x05 \x01(\x04R\tamountSat\x12(\n" +
	"\x10provider_fee_sat\x18\n" +
	" \x01(\x04R\x0eproviderFeeSat\x12&\n" +
	"\x0fnetwork_fee_sat\x18\v \x01(\x04R\rnetworkFeeSat\x12\"\n" +
	"\rtotal_fee_sat\x18\f \x01(\x04R\vtotalFeeSat\x12%\n" +
	"\x0efee_percentage\x18\r \x01(\x01R\rfeePercentage\x12%\n" +
	"\x0elockup_address\x18\x14 \x01(\tR\rlockupAddress\x12#\n" +
	"\rclaim_address\x18\x15 \x01(\tR\fclaimAddress\x12.\n" +
	"\x13user_timeout_blocks\x18\x1e \x01(\rR\x11userTimeoutBlocks\x126\n" +
	"\x17provider_timeout_blocks\x18\x1f \x01(\rR\x15providerTimeoutBlocks\x129\n" +
	"\n" +
	"expires_at\x18( \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"b\n" +
	"\x11CreateSwapRequest\x12\x19\n" +
	"\bquote_id\x18\x01 \x01(\tR\aquoteId\x122\n" +
	"\n" +
	"fee_policy\x18\x02 \x01(\v2\x13.xswallet.FeePolicyR\tfeePolicy\"U\n" +
	"\x0fLockSwapRequest\x12\x17\n" +
	"\aswap_id\x18\x01 \x01(\tR\x06swapId\x12)\n" +
	"\x10expected_version\x18\x02 \x01(\x04R\x0fexpectedVersion\"W\n" +
	"\x11CommitSwapRequest\x12\x17\n" +
	"\aswap_id\x18\x01 \x01(\tR\x06swapId\x12)\n" +
	"\x10expected_version\x18\x02 \x01(\x04R\x0fexpectedVersion\"o\n" +
	"\x11CancelSwapRequest\x12\x17\n" +
	"\aswap_id\x18\x01 \x01(\tR\x06swapId\x12)\n" +
	"\x10expected_version\x18\x02 \x01(\x04R\x0fexpectedVersion\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\")\n" +
	"\x0eGetSwapRequest\x12\x17\n" +
	"\aswap_id\x18\x01 \x01(\tR\x06swapId\"x\n" +
	"\x10ListSwapsRequest\x126\n" +
	"\ffilter_state\x18\x01 \x01(\x0e2\x13.xswallet.SwapStateR\vfilterState\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"L\n" +
	"\x14GetSwapEventsRequest\x12\x17\n" +
	"\aswap_id\x18\x01 \x01(\tR\x06swapId\x12\x1b\n" +
	"\tafter_seq\x18\x02 \x01(\x04R\bafterSeq\"F\n" +
	"\x10WatchSwapRequest\x12\x17\n" +
	"\aswap_id\x18\x01 \x01(\tR\x06swapId\x12\x19\n" +
	"\bfrom_seq\x18\x02 \x01(\x04R\afromSeq\"k\n" +
	"\x14WatchAllSwapsRequest\x128\n" +
	"\rfilter_states\x18\x01 \x03(\x0e2\x13.xswallet.SwapStateR\ffilterStates\x12\x19\n" +
	"\bfrom_seq\x18\x02 \x01(\x04R\afromSeq\"\xa5\a\n" +
	"\fSwapSnapshot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12&\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x12.xswallet.SwapKindR\x04kind\x12)\n" +
	"\x05state\x18\x03 \x01(\x0e2\x13.xswallet.SwapStateR\x05state\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x04R\aversion\x12+\n" +
	"\anetwork\x18\x05 \x01(\x0e2\x11.xswallet.NetworkR\anetwork\x12;\n" +
	"\rlocked_intent\x18\n" +
	" \x01(\v2\x16.xswallet.LockedIntentR\flockedIntent\x12$\n" +
	"\x0eswap_key_index\x18\x14 \x01(\rR\fswapKeyIndex\x12*\n" +
	"\x11preimage_hash_hex\x18\x15 \x01(\tR\x0fpreimageHashHex\x12(\n" +
	"\x10claim_pubkey_hex\x18\x16 \x01(\tR\x0eclaimPubkeyHex\x12*\n" +
	"\x11refund_pubkey_hex\x18\x17 \x01(\tR\x0frefundPubkeyHex\x12(\n" +
	"\x10musig_session_id\x18\x1e \x01(\tR\x0emusigSessionId\x12%\n" +
	"\x0emusig_pubnonce\x18\x1f \x01(\fR\rmusigPubnonce\x12\x1f\n" +
	"\vlockup_txid\x18( \x01(\tR\n" +
	"lockupTxid\x12*\n" +
	"\x11lockup_amount_sat\x18) \x01(\x04R\x0flockupAmountSat\x12\x1d\n" +
	"\n" +
	"claim_txid\x18* \x01(\tR\tclaimTxid\x12\x1f\n" +
	"\vrefund_txid\x18+ \x01(\tR\n" +
	"refundTxid\x120\n" +
	"\x14timeout_block_height\x182 \x01(\rR\x12timeoutBlockHeight\x120\n" +
	"\x14current_block_height\x183 \x01(\rR\x12currentBlockHeight\x12)\n" +
	"\x10blocks_remaining\x184 \x01(\x05R\x0fblocksRemaining\x129\n" +
	"\n" +
	"created_at\x18< \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18= \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12#\n" +
	"\rerror_message\x18F \x01(\tR\ferrorMessage\"\xae\x04\n" +
	"\fLockedIntent\x12&\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x12.xswallet.SwapKindR\x04kind\x12.\n" +
	"\n" +
	"from_chain\x18\x02 \x01(\x0e2\x0f.xswallet.ChainR\tfromChain\x12*\n" +
	"\bto_chain\x18\x03 \x01(\x0e2\x0f.xswallet.ChainR\atoChain\x12\x1d\n" +
	"\n" +
	"amount_sat\x18\x04 \x01(\x04R\tamountSat\x12\x18\n" +
	"\ainvoice\x18\x05 \x01(\tR\ainvoice\x12(\n" +
	"\x10provider_fee_sat\x18\n" +
	" \x01(\x04R\x0eproviderFeeSat\x12&\n" +
	"\x0fnetwork_fee_sat\x18\v \x01(\x04R\rnetworkFeeSat\x12\"\n" +
	"\rtotal_fee_sat\x18\f \x01(\x04R\vtotalFeeSat\x12%\n" +
	"\x0efee_percentage\x18\r \x01(\x01R\rfeePercentage\x12*\n" +
	"\x11provider_quote_id\x18\x14 \x01(\tR\x0fproviderQuoteId\x12%\n" +
	"\x0elockup_address\x18\x15 \x01(\tR\rlockupAddress\x12#\n" +
	"\rclaim_address\x18\x16 \x01(\tR\fclaimAddress\x12!\n" +
	"\fuser_timeout\x18\x1e \x01(\rR\vuserTimeout\x12)\n" +
	"\x10provider_timeout\x18\x1f \x01(\rR\x0fproviderTimeout\"\x91\x02\n" +
	"\tSwapEvent\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\x17\n" +
	"\aswap_id\x18\x02 \x01(\tR\x06swapId\x122\n" +
	"\n" +
	"from_state\x18\x03 \x01(\x0e2\x13.xswallet.SwapStateR\tfromState\x12.\n" +
	"\bto_state\x18\x04 \x01(\x0e2\x13.xswallet.SwapStateR\atoState\x12\x18\n" +
	"\atrigger\x18\x05 \x01(\tR\atrigger\x12!\n" +
	"\fdetails_json\x18\x06 \x01(\tR\vdetailsJson\x128\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"b\n" +
	"\x11ListSwapsResponse\x12,\n" +
	"\x05swaps\x18\x01 \x03(\v2\x16.xswallet.SwapSnapshotR\x05swaps\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"D\n" +
	"\x15GetSwapEventsResponse\x12+\n" +
	"\x06events\x18\x01 \x03(\v2\x13.xswallet.SwapEventR\x06events*j\n" +
	"\bSwapKind\x12\x19\n" +
	"\x15SWAP_KIND_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13SWAP_KIND_SUBMARINE\x10\x01\x12\x15\n" +
	"\x11SWAP_KIND_REVERSE\x10\x02\x12\x13\n" +
	"\x0fSWAP_KIND_CHAIN\x10\x03*\xd9\x03\n" +
	"\tSwapState\x12\x1a\n" +
	"\x16SWAP_STATE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fSWAP_STATE_OPEN\x10\x01\x12\x15\n" +
	"\x11SWAP_STATE_LOCKED\x10\x02\x12\x1d\n" +
	"\x19SWAP_STATE_COMMIT_STARTED\x10\x03\x12\x16\n" +
	"\x12SWAP_STATE_WAITING\x10\x04\x12$\n" +
	" SWAP_STATE_WAITING_CLAIM_DETAILS\x10\x05\x12%\n" +
	"!SWAP_STATE_SIGNING_MUSIG2_PARTIAL\x10\x06\x12'\n" +
	"#SWAP_STATE_SENT_PARTIAL_TO_PROVIDER\x10\a\x12)\n" +
	"%SWAP_STATE_WAITING_PROVIDER_BROADCAST\x10\b\x12\"\n" +
	"\x1eSWAP_STATE_REFUND_COOP_WAITING\x10\t\x12$\n" +
	" SWAP_STATE_FALLBACK_SCRIPT_READY\x10\n" +
	"\x12\x18\n" +
	"\x14SWAP_STATE_REFUNDING\x10\v\x12\x18\n" +
	"\x14SWAP_STATE_COMPLETED\x10\f\x12\x15\n" +
	"\x11SWAP_STATE_FAILED\x10\r\x12\x17\n" +
	"\x13SWAP_STATE_CANCELED\x10\x0e2\xb0\x05\n" +
	"\vSwapService\x12<\n" +
	"\tQuoteSwap\x12\x1a.xswallet.QuoteSwapRequest\x1a\x13.xswallet.SwapQuote\x12A\n" +
	"\n" +
	"CreateSwap\x12\x1b.xswallet.CreateSwapRequest\x1a\x16.xswallet.SwapSnapshot\x12=\n" +
	"\bLockSwap\x12\x19.xswallet.LockSwapRequest\x1a\x16.xswallet.SwapSnapshot\x12A\n" +
	"\n" +
	"CommitSwap\x12\x1b.xswallet.CommitSwapRequest\x1a\x16.xswallet.SwapSnapshot\x12A\n" +
	"\n" +
	"CancelSwap\x12\x1b.xswallet.CancelSwapRequest\x1a\x16.xswallet.SwapSnapshot\x12;\n" +
	"\aGetSwap\x12\x18.xswallet.GetSwapRequest\x1a\x16.xswallet.SwapSnapshot\x12D\n" +
	"\tListSwaps\x12\x1a.xswallet.ListSwapsRequest\x1a\x1b.xswallet.ListSwapsResponse\x12P\n" +
	"\rGetSwapEvents\x12\x1e.xswallet.GetSwapEventsRequest\x1a\x1f.xswallet.GetSwapEventsResponse\x12>\n" +
	"\tWatchSwap\x12\x1a.xswallet.WatchSwapRequest\x1a\x13.xswallet.SwapEvent0\x01\x12F\n" +
	"\rWatchAllSwaps\x12\x1e.xswallet.WatchAllSwapsRequest\x1a\x13.xswallet.SwapEvent0\x01B#Z!github.com/xs-wallet/xscore/protob\x06proto3"

var (
	file_swap_proto_rawDescOnce sync.Once
	file_swap_proto_rawDescData []byte
)

func file_swap_proto_rawDescGZIP() []byte {
	file_swap_proto_rawDescOnce.Do(func() {
		file_swap_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_swap_proto_rawDesc), len(file_swap_proto_rawDesc)))
	})
	return file_swap_proto_rawDescData
}

var file_swap_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_swap_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_swap_proto_goTypes = []any{
	(SwapKind)(0),                 // 0: xswallet.SwapKind
	(SwapState)(0),                // 1: xswallet.SwapState
	(*QuoteSwapRequest)(nil),      // 2: xswallet.QuoteSwapRequest
	(*SubmarineQuoteParams)(nil),  // 3: xswallet.SubmarineQuoteParams
	(*ReverseQuoteParams)(nil),    // 4: xswallet.ReverseQuoteParams
	(*ChainQuoteParams)(nil),      // 5: xswallet.ChainQuoteParams
	(*SwapQuote)(nil),             // 6: xswallet.SwapQuote
	(*CreateSwapRequest)(nil),     // 7: xswallet.CreateSwapRequest
	(*LockSwapRequest)(nil),       // 8: xswallet.LockSwapRequest
	(*CommitSwapRequest)(nil),     // 9: xswallet.CommitSwapRequest
	(*CancelSwapRequest)(nil),     // 10: xswallet.CancelSwapRequest
	(*GetSwapRequest)(nil),        // 11: xswallet.GetSwapRequest
	(*ListSwapsRequest)(nil),      // 12: xswallet.ListSwapsRequest
	(*GetSwapEventsRequest)(nil),  // 13: xswallet.GetSwapEventsRequest
	(*WatchSwapRequest)(nil),      // 14: xswallet.WatchSwapRequest
	(*WatchAllSwapsRequest)(nil),  // 15: xswallet.WatchAllSwapsRequest
	(*SwapSnapshot)(nil),          // 16: xswallet.SwapSnapshot
	(*LockedIntent)(nil),          // 17: xswallet.LockedIntent
	(*SwapEvent)(nil),             // 18: xswallet.SwapEvent
	(*ListSwapsResponse)(nil),     // 19: xswallet.ListSwapsResponse
	(*GetSwapEventsResponse)(nil), // 20: xswallet.GetSwapEventsResponse
	(Chain)(0),                    // 21: xswallet.Chain
	(*timestamppb.Timestamp)(nil), // 22: google.protobuf.Timestamp
	(*FeePolicy)(nil),             // 23: xswallet.FeePolicy
	(Network)(0),                  // 24: xswallet.Network
}
var file_swap_proto_depIdxs = []int32{
	0,  // 0: xswallet.QuoteSwapRequest.kind:type_name -> xswallet.SwapKind
	21, // 1: xswallet.QuoteSwapRequest.from_chain:type_name -> xswallet.Chain
	21, // 2: xswallet.QuoteSwapRequest.to_chain:type_name -> xswallet.Chain
	3,  // 3: xswallet.QuoteSwapRequest.submarine:type_name -> xswallet.SubmarineQuoteParams
	4,  // 4: xswallet.QuoteSwapRequest.reverse:type_name -> xswallet.ReverseQuoteParams
	5,  // 5: xswallet.QuoteSwapRequest.chain:type_name -> xswallet.ChainQuoteParams
	0,  // 6: xswallet.SwapQuote.kind:type_name -> xswallet.SwapKind
	21, // 7: xswallet.SwapQuote.from_chain:type_name -> xswallet.Chain
	21, // 8: xswallet.SwapQuote.to_chain:type_name -> xswallet.Chain
	22, // 9: xswallet.SwapQuote.expires_at:type_name -> google.protobuf.Timestamp
	23, // 10: xswallet.CreateSwapRequest.fee_policy:type_name -> xswallet.FeePolicy
	1,  // 11: xswallet.ListSwapsRequest.filter_state:type_name -> xswallet.SwapState
	1,  // 12: xswallet.WatchAllSwapsRequest.filter_states:type_name -> xswallet.SwapState
	0,  // 13: xswallet.SwapSnapshot.kind:type_name -> xswallet.SwapKind
	1,  // 14: xswallet.SwapSnapshot.state:type_name -> xswallet.SwapState
	24, // 15: xswallet.SwapSnapshot.network:type_name -> xswallet.Network
	17, // 16: xswallet.SwapSnapshot.locked_intent:type_name -> xswallet.LockedIntent
	22, // 17: xswallet.SwapSnapshot.created_at:type_name -> google.protobuf.Timestamp
	22, // 18: xswallet.SwapSnapshot.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 19: xswallet.LockedIntent.kind:type_name -> xswallet.SwapKind
	21, // 20: xswallet.LockedIntent.from_chain:type_name -> xswallet.Chain
	21, // 21: xswallet.LockedIntent.to_chain:type_name -> xswallet.Chain
	1,  // 22: xswallet.SwapEvent.from_state:type_name -> xswallet.SwapState
	1,  // 23: xswallet.SwapEvent.to_state:type_name -> xswallet.SwapState
	22, // 24: xswallet.SwapEvent.timestamp:type_name -> google.protobuf.Timestamp
	16, // 25: xswallet.ListSwapsResponse.swaps:type_name -> xswallet.SwapSnapshot
	18, // 26: xswallet.GetSwapEventsResponse.events:type_name -> xswallet.SwapEvent
	2,  // 27: xswallet.SwapService.QuoteSwap:input_type -> xswallet.QuoteSwapRequest
	7,  // 28: xswallet.SwapService.CreateSwap:input_type -> xswallet.CreateSwapRequest
	8,  // 29: xswallet.SwapService.LockSwap:input_type -> xswallet.LockSwapRequest
	9,  // 30: xswallet.SwapService.CommitSwap:input_type -> xswallet.CommitSwapRequest
	10, // 31: xswallet.SwapService.CancelSwap:input_type -> xswallet.CancelSwapRequest
	11, // 32: xswallet.SwapService.GetSwap:input_type -> xswallet.GetSwapRequest
	12, // 33: xswallet.SwapService.ListSwaps:input_type -> xswallet.ListSwapsRequest
	13, // 34: xswallet.SwapService.GetSwapEvents:input_type -> xswallet.GetSwapEventsRequest
	14, // 35: xswallet.SwapService.WatchSwap:input_type -> xswallet.WatchSwapRequest
	15, // 36: xswallet.SwapService.WatchAllSwaps:input_type -> xswallet.WatchAllSwapsRequest
	6,  // 37: xswallet.SwapService.QuoteSwap:output_type -> xswallet.SwapQuote
	16, // 38: xswallet.SwapService.CreateSwap:output_type -> xswallet.SwapSnapshot
	16, // 39: xswallet.SwapService.LockSwap:output_type -> xswallet.SwapSnapshot
	16, // 40: xswallet.SwapService.CommitSwap:output_type -> xswallet.SwapSnapshot
	16, // 41: xswallet.SwapService.CancelSwap:output_type -> xswallet.SwapSnapshot
	16, // 42: xswallet.SwapService.GetSwap:output_type -> xswallet.SwapSnapshot
	19, // 43: xswallet.SwapService.ListSwaps:output_type -> xswallet.ListSwapsResponse
	20, // 44: xswallet.SwapService.GetSwapEvents:output_type -> xswallet.GetSwapEventsResponse
	18, // 45: xswallet.SwapService.WatchSwap:output_type -> xswallet.SwapEvent
	18, // 46: xswallet.SwapService.WatchAllSwaps:output_type -> xswallet.SwapEvent
	37, // [37:47] is the sub-list for method output_type
	27, // [27:37] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_swap_proto_init() }
func file_swap_proto_init() {
	if File_swap_proto != nil {
		return
	}
	file_common_proto_init()
	file_swap_proto_msgTypes[0].OneofWrappers = []any{
		(*QuoteSwapRequest_Submarine)(nil),
		(*QuoteSwapRequest_Reverse)(nil),
		(*QuoteSwapRequest_Chain)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_swap_proto_rawDesc), len(file_swap_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_swap_proto_goTypes,
		DependencyIndexes: file_swap_proto_depIdxs,
		EnumInfos:         file_swap_proto_enumTypes,
		MessageInfos:      file_swap_proto_msgTypes,
	}.Build()
	File_swap_proto = out.File
	file_swap_proto_goTypes = nil
	file_swap_proto_depIdxs = nil
}
