// XS Wallet - Wallet Service Protocol
// Gerenciamento de carteira, balances, endereços

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: wallet.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WalletService_InitializeVault_FullMethodName    = "/xswallet.WalletService/InitializeVault"
	WalletService_UnlockVault_FullMethodName        = "/xswallet.WalletService/UnlockVault"
	WalletService_LockVault_FullMethodName          = "/xswallet.WalletService/LockVault"
	WalletService_GetVaultStatus_FullMethodName     = "/xswallet.WalletService/GetVaultStatus"
	WalletService_GetBackupStatus_FullMethodName    = "/xswallet.WalletService/GetBackupStatus"
	WalletService_MarkBackupComplete_FullMethodName = "/xswallet.WalletService/MarkBackupComplete"
	WalletService_GetBalance_FullMethodName         = "/xswallet.WalletService/GetBalance"
	WalletService_GetAllBalances_FullMethodName     = "/xswallet.WalletService/GetAllBalances"
	WalletService_GetNewAddress_FullMethodName      = "/xswallet.WalletService/GetNewAddress"
	WalletService_ListAddresses_FullMethodName      = "/xswallet.WalletService/ListAddresses"
	WalletService_ListUtxos_FullMethodName          = "/xswallet.WalletService/ListUtxos"
	WalletService_ListTransactions_FullMethodName   = "/xswallet.WalletService/ListTransactions"
	WalletService_WatchBalances_FullMethodName      = "/xswallet.WalletService/WatchBalances"
)

// WalletServiceClient is the client API for WalletService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WalletServiceClient interface {
	// Vault (seed/keys)
	InitializeVault(ctx context.Context, in *InitializeVaultRequest, opts ...grpc.CallOption) (*InitializeVaultResponse, error)
	UnlockVault(ctx context.Context, in *UnlockVaultRequest, opts ...grpc.CallOption) (*UnlockVaultResponse, error)
	LockVault(ctx context.Context, in *LockVaultRequest, opts ...grpc.CallOption) (*LockVaultResponse, error)
	GetVaultStatus(ctx context.Context, in *GetVaultStatusRequest, opts ...grpc.CallOption) (*VaultStatus, error)
	// Backup
	GetBackupStatus(ctx context.Context, in *GetBackupStatusRequest, opts ...grpc.CallOption) (*BackupStatus, error)
	MarkBackupComplete(ctx context.Context, in *MarkBackupCompleteRequest, opts ...grpc.CallOption) (*BackupStatus, error)
	// Balances
	GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*BalanceResponse, error)
	GetAllBalances(ctx context.Context, in *GetAllBalancesRequest, opts ...grpc.CallOption) (*AllBalancesResponse, error)
	// Addresses
	GetNewAddress(ctx context.Context, in *GetNewAddressRequest, opts ...grpc.CallOption) (*AddressResponse, error)
	ListAddresses(ctx context.Context, in *ListAddressesRequest, opts ...grpc.CallOption) (*ListAddressesResponse, error)
	// UTXOs
	ListUtxos(ctx context.Context, in *ListUtxosRequest, opts ...grpc.CallOption) (*ListUtxosResponse, error)
	// Transactions
	ListTransactions(ctx context.Context, in *ListTransactionsRequest, opts ...grpc.CallOption) (*ListTransactionsResponse, error)
	// Streaming
	WatchBalances(ctx context.Context, in *WatchBalancesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BalanceUpdate], error)
}

type walletServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWalletServiceClient(cc grpc.ClientConnInterface) WalletServiceClient {
	return &walletServiceClient{cc}
}

func (c *walletServiceClient) InitializeVault(ctx context.Context, in *InitializeVaultRequest, opts ...grpc.CallOption) (*InitializeVaultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitializeVaultResponse)
	err := c.cc.Invoke(ctx, WalletService_InitializeVault_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) UnlockVault(ctx context.Context, in *UnlockVaultRequest, opts ...grpc.CallOption) (*UnlockVaultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnlockVaultResponse)
	err := c.cc.Invoke(ctx, WalletService_UnlockVault_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) LockVault(ctx context.Context, in *LockVaultRequest, opts ...grpc.CallOption) (*LockVaultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LockVaultResponse)
	err := c.cc.Invoke(ctx, WalletService_LockVault_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) GetVaultStatus(ctx context.Context, in *GetVaultStatusRequest, opts ...grpc.CallOption) (*VaultStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VaultStatus)
	err := c.cc.Invoke(ctx, WalletService_GetVaultStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) GetBackupStatus(ctx context.Context, in *GetBackupStatusRequest, opts ...grpc.CallOption) (*BackupStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BackupStatus)
	err := c.cc.Invoke(ctx, WalletService_GetBackupStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) MarkBackupComplete(ctx context.Context, in *MarkBackupCompleteRequest, opts ...grpc.CallOption) (*BackupStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BackupStatus)
	err := c.cc.Invoke(ctx, WalletService_MarkBackupComplete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*BalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BalanceResponse)
	err := c.cc.Invoke(ctx, WalletService_GetBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) GetAllBalances(ctx context.Context, in *GetAllBalancesRequest, opts ...grpc.CallOption) (*AllBalancesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AllBalancesResponse)
	err := c.cc.Invoke(ctx, WalletService_GetAllBalances_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) GetNewAddress(ctx context.Context, in *GetNewAddressRequest, opts ...grpc.CallOption) (*AddressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddressResponse)
	err := c.cc.Invoke(ctx, WalletService_GetNewAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) ListAddresses(ctx context.Context, in *ListAddressesRequest, opts ...grpc.CallOption) (*ListAddressesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAddressesResponse)
	err := c.cc.Invoke(ctx, WalletService_ListAddresses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) ListUtxos(ctx context.Context, in *ListUtxosRequest, opts ...grpc.CallOption) (*ListUtxosResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUtxosResponse)
	err := c.cc.Invoke(ctx, WalletService_ListUtxos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) ListTransactions(ctx context.Context, in *ListTransactionsRequest, opts ...grpc.CallOption) (*ListTransactionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTransactionsResponse)
	err := c.cc.Invoke(ctx, WalletService_ListTransactions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) WatchBalances(ctx context.Context, in *WatchBalancesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BalanceUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WalletService_ServiceDesc.Streams[0], WalletService_WatchBalances_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchBalancesRequest, BalanceUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WalletService_WatchBalancesClient = grpc.ServerStreamingClient[BalanceUpdate]

// WalletServiceServer is the server API for WalletService service.
// All implementations must embed UnimplementedWalletServiceServer
// for forward compatibility.
type WalletServiceServer interface {
	// Vault (seed/keys)
	InitializeVault(context.Context, *InitializeVaultRequest) (*InitializeVaultResponse, error)
	UnlockVault(context.Context, *UnlockVaultRequest) (*UnlockVaultResponse, error)
	LockVault(context.Context, *LockVaultRequest) (*LockVaultResponse, error)
	GetVaultStatus(context.Context, *GetVaultStatusRequest) (*VaultStatus, error)
	// Backup
	GetBackupStatus(context.Context, *GetBackupStatusRequest) (*BackupStatus, error)
	MarkBackupComplete(context.Context, *MarkBackupCompleteRequest) (*BackupStatus, error)
	// Balances
	GetBalance(context.Context, *GetBalanceRequest) (*BalanceResponse, error)
	GetAllBalances(context.Context, *GetAllBalancesRequest) (*AllBalancesResponse, error)
	// Addresses
	GetNewAddress(context.Context, *GetNewAddressRequest) (*AddressResponse, error)
	ListAddresses(context.Context, *ListAddressesRequest) (*ListAddressesResponse, error)
	// UTXOs
	ListUtxos(context.Context, *ListUtxosRequest) (*ListUtxosResponse, error)
	// Transactions
	ListTransactions(context.Context, *ListTransactionsRequest) (*ListTransactionsResponse, error)
	// Streaming
	WatchBalances(*WatchBalancesRequest, grpc.ServerStreamingServer[BalanceUpdate]) error
	mustEmbedUnimplementedWalletServiceServer()
}

// UnimplementedWalletServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWalletServiceServer struct{}

func (UnimplementedWalletServiceServer) InitializeVault(context.Context, *InitializeVaultRequest) (*InitializeVaultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InitializeVault not implemented")
}
func (UnimplementedWalletServiceServer) UnlockVault(context.Context, *UnlockVaultRequest) (*UnlockVaultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnlockVault not implemented")
}
func (UnimplementedWalletServiceServer) LockVault(context.Context, *LockVaultRequest) (*LockVaultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LockVault not implemented")
}
func (UnimplementedWalletServiceServer) GetVaultStatus(context.Context, *GetVaultStatusRequest) (*VaultStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVaultStatus not implemented")
}
func (UnimplementedWalletServiceServer) GetBackupStatus(context.Context, *GetBackupStatusRequest) (*BackupStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBackupStatus not implemented")
}
func (UnimplementedWalletServiceServer) MarkBackupComplete(context.Context, *MarkBackupCompleteRequest) (*BackupStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkBackupComplete not implemented")
}
func (UnimplementedWalletServiceServer) GetBalance(context.Context, *GetBalanceRequest) (*BalanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBalance not implemented")
}
func (UnimplementedWalletServiceServer) GetAllBalances(context.Context, *GetAllBalancesRequest) (*AllBalancesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllBalances not implemented")
}
func (UnimplementedWalletServiceServer) GetNewAddress(context.Context, *GetNewAddressRequest) (*AddressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNewAddress not implemented")
}
func (UnimplementedWalletServiceServer) ListAddresses(context.Context, *ListAddressesRequest) (*ListAddressesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAddresses not implemented")
}
func (UnimplementedWalletServiceServer) ListUtxos(context.Context, *ListUtxosRequest) (*ListUtxosResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUtxos not implemented")
}
func (UnimplementedWalletServiceServer) ListTransactions(context.Context, *ListTransactionsRequest) (*ListTransactionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTransactions not implemented")
}
func (UnimplementedWalletServiceServer) WatchBalances(*WatchBalancesRequest, grpc.ServerStreamingServer[BalanceUpdate]) error {
	return status.Error(codes.Unimplemented, "method WatchBalances not implemented")
}
func (UnimplementedWalletServiceServer) mustEmbedUnimplementedWalletServiceServer() {}
func (UnimplementedWalletServiceServer) testEmbeddedByValue()                       {}

// UnsafeWalletServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WalletServiceServer will
// result in compilation errors.
type UnsafeWalletServiceServer interface {
	mustEmbedUnimplementedWalletServiceServer()
}

func RegisterWalletServiceServer(s grpc.ServiceRegistrar, srv WalletServiceServer) {
	// If the following call panics, it indicates UnimplementedWalletServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WalletService_ServiceDesc, srv)
}

func _WalletService_InitializeVault_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitializeVaultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).InitializeVault(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_InitializeVault_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).InitializeVault(ctx, req.(*InitializeVaultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_UnlockVault_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlockVaultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).UnlockVault(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_UnlockVault_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).UnlockVault(ctx, req.(*UnlockVaultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_LockVault_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockVaultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).LockVault(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_LockVault_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).LockVault(ctx, req.(*LockVaultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_GetVaultStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVaultStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetVaultStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_GetVaultStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetVaultStatus(ctx, req.(*GetVaultStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_GetBackupStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBackupStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetBackupStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_GetBackupStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetBackupStatus(ctx, req.(*GetBackupStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_MarkBackupComplete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkBackupCompleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).MarkBackupComplete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_MarkBackupComplete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).MarkBackupComplete(ctx, req.(*MarkBackupCompleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_GetBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetBalance(ctx, req.(*GetBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_GetAllBalances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllBalancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetAllBalances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_GetAllBalances_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetAllBalances(ctx, req.(*GetAllBalancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_GetNewAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNewAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetNewAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_GetNewAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetNewAddress(ctx, req.(*GetNewAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_ListAddresses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAddressesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).ListAddresses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_ListAddresses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).ListAddresses(ctx, req.(*ListAddressesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_ListUtxos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUtxosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).ListUtxos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_ListUtxos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).ListUtxos(ctx, req.(*ListUtxosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_ListTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).ListTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_ListTransactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).ListTransactions(ctx, req.(*ListTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_WatchBalances_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchBalancesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WalletServiceServer).WatchBalances(m, &grpc.GenericServerStream[WatchBalancesRequest, BalanceUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WalletService_WatchBalancesServer = grpc.ServerStreamingServer[BalanceUpdate]

// WalletService_ServiceDesc is the grpc.ServiceDesc for WalletService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WalletService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xswallet.WalletService",
	HandlerType: (*WalletServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitializeVault",
			Handler:    _WalletService_InitializeVault_Handler,
		},
		{
			MethodName: "UnlockVault",
			Handler:    _WalletService_UnlockVault_Handler,
		},
		{
			MethodName: "LockVault",
			Handler:    _WalletService_LockVault_Handler,
		},
		{
			MethodName: "GetVaultStatus",
			Handler:    _WalletService_GetVaultStatus_Handler,
		},
		{
			MethodName: "GetBackupStatus",
			Handler:    _WalletService_GetBackupStatus_Handler,
		},
		{
			MethodName: "MarkBackupComplete",
			Handler:    _WalletService_MarkBackupComplete_Handler,
		},
		{
			MethodName: "GetBalance",
			Handler:    _WalletService_GetBalance_Handler,
		},
		{
			MethodName: "GetAllBalances",
			Handler:    _WalletService_GetAllBalances_Handler,
		},
		{
			MethodName: "GetNewAddress",
			Handler:    _WalletService_GetNewAddress_Handler,
		},
		{
			MethodName: "ListAddresses",
			Handler:    _WalletService_ListAddresses_Handler,
		},
		{
			MethodName: "ListUtxos",
			Handler:    _WalletService_ListUtxos_Handler,
		},
		{
			MethodName: "ListTransactions",
			Handler:    _WalletService_ListTransactions_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchBalances",
			Handler:       _WalletService_WatchBalances_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "wallet.proto",
}
