// XS Wallet - Wallet Service Protocol
// Gerenciamento de carteira, balances, endereços

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: wallet.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VaultStatus_State int32

const (
	VaultStatus_STATE_UNSPECIFIED     VaultStatus_State = 0
	VaultStatus_STATE_NOT_INITIALIZED VaultStatus_State = 1 // Sem seed
	VaultStatus_STATE_LOCKED          VaultStatus_State = 2 // Seed existe mas vault trancado
	VaultStatus_STATE_UNLOCKED        VaultStatus_State = 3 // Pronto para operar
	VaultStatus_STATE_LOCKED_OUT      VaultStatus_State = 4 // Muitas tentativas erradas
)

// Enum value maps for VaultStatus_State.
var (
	VaultStatus_State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "STATE_NOT_INITIALIZED",
		2: "STATE_LOCKED",
		3: "STATE_UNLOCKED",
		4: "STATE_LOCKED_OUT",
	}
	VaultStatus_State_value = map[string]int32{
		"STATE_UNSPECIFIED":     0,
		"STATE_NOT_INITIALIZED": 1,
		"STATE_LOCKED":          2,
		"STATE_UNLOCKED":        3,
		"STATE_LOCKED_OUT":      4,
	}
)

func (x VaultStatus_State) Enum() *VaultStatus_State {
	p := new(VaultStatus_State)
	*p = x
	return p
}

func (x VaultStatus_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VaultStatus_State) Descriptor() protoreflect.EnumDescriptor {
	return file_wallet_proto_enumTypes[0].Descriptor()
}

func (VaultStatus_State) Type() protoreflect.EnumType {
	return &file_wallet_proto_enumTypes[0]
}

func (x VaultStatus_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VaultStatus_State.Descriptor instead.
func (VaultStatus_State) EnumDescriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{9, 0}
}

type InitializeVaultRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to SeedSource:
	//
	//	*InitializeVaultRequest_Generate
	//	*InitializeVaultRequest_Import
	SeedSource    isInitializeVaultRequest_SeedSource `protobuf_oneof:"seed_source"`
	Pin           string                              `protobuf:"bytes,3,opt,name=pin,proto3" json:"pin,omitempty"` // PIN para criptografar vault
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeVaultRequest) Reset() {
	*x = InitializeVaultRequest{}
	mi := &file_wallet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeVaultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeVaultRequest) ProtoMessage() {}

func (x *InitializeVaultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeVaultRequest.ProtoReflect.Descriptor instead.
func (*InitializeVaultRequest) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{0}
}

func (x *InitializeVaultRequest) GetSeedSource() isInitializeVaultRequest_SeedSource {
	if x != nil {
		return x.SeedSource
	}
	return nil
}

func (x *InitializeVaultRequest) GetGenerate() *GenerateNewSeed {
	if x != nil {
		if x, ok := x.SeedSource.(*InitializeVaultRequest_Generate); ok {
			return x.Generate
		}
	}
	return nil
}

func (x *InitializeVaultRequest) GetImport() *ImportExistingSeed {
	if x != nil {
		if x, ok := x.SeedSource.(*InitializeVaultRequest_Import); ok {
			return x.Import
		}
	}
	return nil
}

func (x *InitializeVaultRequest) GetPin() string {
	if x != nil {
		return x.Pin
	}
	return ""
}

type isInitializeVaultRequest_SeedSource interface {
	isInitializeVaultRequest_SeedSource()
}

type InitializeVaultRequest_Generate struct {
	Generate *GenerateNewSeed `protobuf:"bytes,1,opt,name=generate,proto3,oneof"`
}

type InitializeVaultRequest_Import struct {
	Import *ImportExistingSeed `protobuf:"bytes,2,opt,name=import,proto3,oneof"`
}

func (*InitializeVaultRequest_Generate) isInitializeVaultRequest_SeedSource() {}

func (*InitializeVaultRequest_Import) isInitializeVaultRequest_SeedSource() {}

type GenerateNewSeed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WordCount     int32                  `protobuf:"varint,1,opt,name=word_count,json=wordCount,proto3" json:"word_count,omitempty"` // 12 ou 24
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateNewSeed) Reset() {
	*x = GenerateNewSeed{}
	mi := &file_wallet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateNewSeed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateNewSeed) ProtoMessage() {}

func (x *GenerateNewSeed) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateNewSeed.ProtoReflect.Descriptor instead.
func (*GenerateNewSeed) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateNewSeed) GetWordCount() int32 {
	if x != nil {
		return x.WordCount
	}
	return 0
}

type ImportExistingSeed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mnemonic      string                 `protobuf:"bytes,1,opt,name=mnemonic,proto3" json:"mnemonic,omitempty"`
	Passphrase    string                 `protobuf:"bytes,2,opt,name=passphrase,proto3" json:"passphrase,omitempty"` // BIP39 passphrase (opcional)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportExistingSeed) Reset() {
	*x = ImportExistingSeed{}
	mi := &file_wallet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportExistingSeed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportExistingSeed) ProtoMessage() {}

func (x *ImportExistingSeed) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportExistingSeed.ProtoReflect.Descriptor instead.
func (*ImportExistingSeed) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{2}
}

func (x *ImportExistingSeed) GetMnemonic() string {
	if x != nil {
		return x.Mnemonic
	}
	return ""
}

func (x *ImportExistingSeed) GetPassphrase() string {
	if x != nil {
		return x.Passphrase
	}
	return ""
}

type InitializeVaultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Mnemonic      string                 `protobuf:"bytes,2,opt,name=mnemonic,proto3" json:"mnemonic,omitempty"`                    // Só retornado em generate, NUNCA armazenar
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // Session ID para autenticação
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeVaultResponse) Reset() {
	*x = InitializeVaultResponse{}
	mi := &file_wallet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeVaultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeVaultResponse) ProtoMessage() {}

func (x *InitializeVaultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeVaultResponse.ProtoReflect.Descriptor instead.
func (*InitializeVaultResponse) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{3}
}

func (x *InitializeVaultResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InitializeVaultResponse) GetMnemonic() string {
	if x != nil {
		return x.Mnemonic
	}
	return ""
}

func (x *InitializeVaultResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *InitializeVaultResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type UnlockVaultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pin           string                 `protobuf:"bytes,1,opt,name=pin,proto3" json:"pin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlockVaultRequest) Reset() {
	*x = UnlockVaultRequest{}
	mi := &file_wallet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockVaultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockVaultRequest) ProtoMessage() {}

func (x *UnlockVaultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockVaultRequest.ProtoReflect.Descriptor instead.
func (*UnlockVaultRequest) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{4}
}

func (x *UnlockVaultRequest) GetPin() string {
	if x != nil {
		return x.Pin
	}
	return ""
}

type UnlockVaultResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	SessionId         string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // Session ID válido até lock
	ErrorMessage      string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	AttemptsRemaining int32                  `protobuf:"varint,4,opt,name=attempts_remaining,json=attemptsRemaining,proto3" json:"attempts_remaining,omitempty"` // Tentativas antes de lockout
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UnlockVaultResponse) Reset() {
	*x = UnlockVaultResponse{}
	mi := &file_wallet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockVaultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockVaultResponse) ProtoMessage() {}

func (x *UnlockVaultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockVaultResponse.ProtoReflect.Descriptor instead.
func (*UnlockVaultResponse) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{5}
}

func (x *UnlockVaultResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnlockVaultResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *UnlockVaultResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *UnlockVaultResponse) GetAttemptsRemaining() int32 {
	if x != nil {
		return x.AttemptsRemaining
	}
	return 0
}

type LockVaultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // Invalidar sessão
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockVaultRequest) Reset() {
	*x = LockVaultRequest{}
	mi := &file_wallet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockVaultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockVaultRequest) ProtoMessage() {}

func (x *LockVaultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockVaultRequest.ProtoReflect.Descriptor instead.
func (*LockVaultRequest) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{6}
}

func (x *LockVaultRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type LockVaultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockVaultResponse) Reset() {
	*x = LockVaultResponse{}
	mi := &file_wallet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockVaultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockVaultResponse) ProtoMessage() {}

func (x *LockVaultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockVaultResponse.ProtoReflect.Descriptor instead.
func (*LockVaultResponse) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{7}
}

func (x *LockVaultResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetVaultStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVaultStatusRequest) Reset() {
	*x = GetVaultStatusRequest{}
	mi := &file_wallet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVaultStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVaultStatusRequest) ProtoMessage() {}

func (x *GetVaultStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVaultStatusRequest.ProtoReflect.Descriptor instead.
func (*GetVaultStatusRequest) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{8}
}

type VaultStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	State          VaultStatus_State      `protobuf:"varint,1,opt,name=state,proto3,enum=xswallet.VaultStatus_State" json:"state,omitempty"`
	FailedAttempts int32                  `protobuf:"varint,2,opt,name=failed_attempts,json=failedAttempts,proto3" json:"failed_attempts,omitempty"`
	LockoutUntil   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=lockout_until,json=lockoutUntil,proto3" json:"lockout_until,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VaultStatus) Reset() {
	*x = VaultStatus{}
	mi := &file_wallet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultStatus) ProtoMessage() {}

func (x *VaultStatus) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultStatus.ProtoReflect.Descriptor instead.
func (*VaultStatus) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{9}
}

func (x *VaultStatus) GetState() VaultStatus_State {
	if x != nil {
		return x.State
	}
	return VaultStatus_STATE_UNSPECIFIED
}

func (x *VaultStatus) GetFailedAttempts() int32 {
	if x != nil {
		return x.FailedAttempts
	}
	return 0
}

func (x *VaultStatus) GetLockoutUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.LockoutUntil
	}
	return nil
}

type GetBackupStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBackupStatusRequest) Reset() {
	*x = GetBackupStatusRequest{}
	mi := &file_wallet_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBackupStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBackupStatusRequest) ProtoMessage() {}

func (x *GetBackupStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBackupStatusRequest.ProtoReflect.Descriptor instead.
func (*GetBackupStatusRequest) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{10}
}

type BackupStatus struct {
	state                          protoimpl.MessageState `protogen:"open.v1"`
	HasPendingSwapsRequiringBackup bool                   `protobuf:"varint,1,opt,name=has_pending_swaps_requiring_backup,json=hasPendingSwapsRequiringBackup,proto3" json:"has_pending_swaps_requiring_backup,omitempty"` // Swaps com preimage R no DB
	PendingSwapCount               int32                  `protobuf:"varint,2,opt,name=pending_swap_count,json=pendingSwapCount,proto3" json:"pending_swap_count,omitempty"`
	LastBackupAt                   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_backup_at,json=lastBackupAt,proto3" json:"last_backup_at,omitempty"`
	BackupRecommended              bool                   `protobuf:"varint,4,opt,name=backup_recommended,json=backupRecommended,proto3" json:"backup_recommended,omitempty"`
	WarningMessage                 string                 `protobuf:"bytes,5,opt,name=warning_message,json=warningMessage,proto3" json:"warning_message,omitempty"` // "You have 2 pending swaps. Backup required!"
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *BackupStatus) Reset() {
	*x = BackupStatus{}
	mi := &file_wallet_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupStatus) ProtoMessage() {}

func (x *BackupStatus) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupStatus.ProtoReflect.Descriptor instead.
func (*BackupStatus) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{11}
}

func (x *BackupStatus) GetHasPendingSwapsRequiringBackup() bool {
	if x != nil {
		return x.HasPendingSwapsRequiringBackup
	}
	return false
}

func (x *BackupStatus) GetPendingSwapCount() int32 {
	if x != nil {
		return x.PendingSwapCount
	}
	return 0
}

func (x *BackupStatus) GetLastBackupAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastBackupAt
	}
	return nil
}

func (x *BackupStatus) GetBackupRecommended() bool {
	if x != nil {
		return x.BackupRecommended
	}
	return false
}

func (x *BackupStatus) GetWarningMessage() string {
	if x != nil {
		return x.WarningMessage
	}
	return ""
}

type MarkBackupCompleteRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BackupTimestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=backup_timestamp,json=backupTimestamp,proto3" json:"backup_timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MarkBackupCompleteRequest) Reset() {
	*x = MarkBackupCompleteRequest{}
	mi := &file_wallet_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkBackupCompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkBackupCompleteRequest) ProtoMessage() {}

func (x *MarkBackupCompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkBackupCompleteRequest.ProtoReflect.Descriptor instead.
func (*MarkBackupCompleteRequest) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{12}
}

func (x *MarkBackupCompleteRequest) GetBackupTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.BackupTimestamp
	}
	return nil
}

type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chain         Chain                  `protobuf:"varint,1,opt,name=chain,proto3,enum=xswallet.Chain" json:"chain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_wallet_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{13}
}

func (x *GetBalanceRequest) GetChain() Chain {
	if x != nil {
		return x.Chain
	}
	return Chain_CHAIN_UNSPECIFIED
}

type BalanceResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Chain          Chain                  `protobuf:"varint,1,opt,name=chain,proto3,enum=xswallet.Chain" json:"chain,omitempty"`
	ConfirmedSat   uint64                 `protobuf:"varint,2,opt,name=confirmed_sat,json=confirmedSat,proto3" json:"confirmed_sat,omitempty"`
	UnconfirmedSat uint64                 `protobuf:"varint,3,opt,name=unconfirmed_sat,json=unconfirmedSat,proto3" json:"unconfirmed_sat,omitempty"`
	PendingSwapSat uint64                 `protobuf:"varint,4,opt,name=pending_swap_sat,json=pendingSwapSat,proto3" json:"pending_swap_sat,omitempty"` // Em swaps ativos
	TotalSat       uint64                 `protobuf:"varint,5,opt,name=total_sat,json=totalSat,proto3" json:"total_sat,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BalanceResponse) Reset() {
	*x = BalanceResponse{}
	mi := &file_wallet_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceResponse) ProtoMessage() {}

func (x *BalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceResponse.ProtoReflect.Descriptor instead.
func (*BalanceResponse) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{14}
}

func (x *BalanceResponse) GetChain() Chain {
	if x != nil {
		return x.Chain
	}
	return Chain_CHAIN_UNSPECIFIED
}

func (x *BalanceResponse) GetConfirmedSat() uint64 {
	if x != nil {
		return x.ConfirmedSat
	}
	return 0
}

func (x *BalanceResponse) GetUnconfirmedSat() uint64 {
	if x != nil {
		return x.UnconfirmedSat
	}
	return 0
}

func (x *BalanceResponse) GetPendingSwapSat() uint64 {
	if x != nil {
		return x.PendingSwapSat
	}
	return 0
}

func (x *BalanceResponse) GetTotalSat() uint64 {
	if x != nil {
		return x.TotalSat
	}
	return 0
}

type GetAllBalancesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllBalancesRequest) Reset() {
	*x = GetAllBalancesRequest{}
	mi := &file_wallet_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllBalancesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllBalancesRequest) ProtoMessage() {}

func (x *GetAllBalancesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllBalancesRequest.ProtoReflect.Descriptor instead.
func (*GetAllBalancesRequest) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{15}
}

type AllBalancesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Btc           *BalanceResponse       `protobuf:"bytes,1,opt,name=btc,proto3" json:"btc,omitempty"`
	Liquid        *BalanceResponse       `protobuf:"bytes,2,opt,name=liquid,proto3" json:"liquid,omitempty"`
	Ln            *BalanceResponse       `protobuf:"bytes,3,opt,name=ln,proto3" json:"ln,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllBalancesResponse) Reset() {
	*x = AllBalancesResponse{}
	mi := &file_wallet_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllBalancesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllBalancesResponse) ProtoMessage() {}

func (x *AllBalancesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllBalancesResponse.ProtoReflect.Descriptor instead.
func (*AllBalancesResponse) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{16}
}

func (x *AllBalancesResponse) GetBtc() *BalanceResponse {
	if x != nil {
		return x.Btc
	}
	return nil
}

func (x *AllBalancesResponse) GetLiquid() *BalanceResponse {
	if x != nil {
		return x.Liquid
	}
	return nil
}

func (x *AllBalancesResponse) GetLn() *BalanceResponse {
	if x != nil {
		return x.Ln
	}
	return nil
}

type WatchBalancesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchBalancesRequest) Reset() {
	*x = WatchBalancesRequest{}
	mi := &file_wallet_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchBalancesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchBalancesRequest) ProtoMessage() {}

func (x *WatchBalancesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchBalancesRequest.ProtoReflect.Descriptor instead.
func (*WatchBalancesRequest) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{17}
}

type BalanceUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chain         Chain                  `protobuf:"varint,1,opt,name=chain,proto3,enum=xswallet.Chain" json:"chain,omitempty"`
	Balance       *BalanceResponse       `protobuf:"bytes,2,opt,name=balance,proto3" json:"balance,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"` // "new_tx", "confirmation", "swap_completed"
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceUpdate) Reset() {
	*x = BalanceUpdate{}
	mi := &file_wallet_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceUpdate) ProtoMessage() {}

func (x *BalanceUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceUpdate.ProtoReflect.Descriptor instead.
func (*BalanceUpdate) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{18}
}

func (x *BalanceUpdate) GetChain() Chain {
	if x != nil {
		return x.Chain
	}
	return Chain_CHAIN_UNSPECIFIED
}

func (x *BalanceUpdate) GetBalance() *BalanceResponse {
	if x != nil {
		return x.Balance
	}
	return nil
}

func (x *BalanceUpdate) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *BalanceUpdate) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type GetNewAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chain         Chain                  `protobuf:"varint,1,opt,name=chain,proto3,enum=xswallet.Chain" json:"chain,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"` // Label opcional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNewAddressRequest) Reset() {
	*x = GetNewAddressRequest{}
	mi := &file_wallet_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNewAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNewAddressRequest) ProtoMessage() {}

func (x *GetNewAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNewAddressRequest.ProtoReflect.Descriptor instead.
func (*GetNewAddressRequest) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{19}
}

func (x *GetNewAddressRequest) GetChain() Chain {
	if x != nil {
		return x.Chain
	}
	return Chain_CHAIN_UNSPECIFIED
}

func (x *GetNewAddressRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type AddressResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Address        string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Chain          Chain                  `protobuf:"varint,2,opt,name=chain,proto3,enum=xswallet.Chain" json:"chain,omitempty"`
	DerivationPath string                 `protobuf:"bytes,3,opt,name=derivation_path,json=derivationPath,proto3" json:"derivation_path,omitempty"`
	Label          string                 `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AddressResponse) Reset() {
	*x = AddressResponse{}
	mi := &file_wallet_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressResponse) ProtoMessage() {}

func (x *AddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressResponse.ProtoReflect.Descriptor instead.
func (*AddressResponse) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{20}
}

func (x *AddressResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AddressResponse) GetChain() Chain {
	if x != nil {
		return x.Chain
	}
	return Chain_CHAIN_UNSPECIFIED
}

func (x *AddressResponse) GetDerivationPath() string {
	if x != nil {
		return x.DerivationPath
	}
	return ""
}

func (x *AddressResponse) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type ListAddressesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chain         Chain                  `protobuf:"varint,1,opt,name=chain,proto3,enum=xswallet.Chain" json:"chain,omitempty"`
	IncludeUsed   bool                   `protobuf:"varint,2,opt,name=include_used,json=includeUsed,proto3" json:"include_used,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAddressesRequest) Reset() {
	*x = ListAddressesRequest{}
	mi := &file_wallet_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAddressesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAddressesRequest) ProtoMessage() {}

func (x *ListAddressesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAddressesRequest.ProtoReflect.Descriptor instead.
func (*ListAddressesRequest) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{21}
}

func (x *ListAddressesRequest) GetChain() Chain {
	if x != nil {
		return x.Chain
	}
	return Chain_CHAIN_UNSPECIFIED
}

func (x *ListAddressesRequest) GetIncludeUsed() bool {
	if x != nil {
		return x.IncludeUsed
	}
	return false
}

type ListAddressesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addresses     []*AddressInfo         `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAddressesResponse) Reset() {
	*x = ListAddressesResponse{}
	mi := &file_wallet_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAddressesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAddressesResponse) ProtoMessage() {}

func (x *ListAddressesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAddressesResponse.ProtoReflect.Descriptor instead.
func (*ListAddressesResponse) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{22}
}

func (x *ListAddressesResponse) GetAddresses() []*AddressInfo {
	if x != nil {
		return x.Addresses
	}
	return nil
}

type AddressInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Address        string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Chain          Chain                  `protobuf:"varint,2,opt,name=chain,proto3,enum=xswallet.Chain" json:"chain,omitempty"`
	DerivationPath string                 `protobuf:"bytes,3,opt,name=derivation_path,json=derivationPath,proto3" json:"derivation_path,omitempty"`
	Label          string                 `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	Used           bool                   `protobuf:"varint,5,opt,name=used,proto3" json:"used,omitempty"`
	BalanceSat     uint64                 `protobuf:"varint,6,opt,name=balance_sat,json=balanceSat,proto3" json:"balance_sat,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AddressInfo) Reset() {
	*x = AddressInfo{}
	mi := &file_wallet_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressInfo) ProtoMessage() {}

func (x *AddressInfo) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressInfo.ProtoReflect.Descriptor instead.
func (*AddressInfo) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{23}
}

func (x *AddressInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AddressInfo) GetChain() Chain {
	if x != nil {
		return x.Chain
	}
	return Chain_CHAIN_UNSPECIFIED
}

func (x *AddressInfo) GetDerivationPath() string {
	if x != nil {
		return x.DerivationPath
	}
	return ""
}

func (x *AddressInfo) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *AddressInfo) GetUsed() bool {
	if x != nil {
		return x.Used
	}
	return false
}

func (x *AddressInfo) GetBalanceSat() uint64 {
	if x != nil {
		return x.BalanceSat
	}
	return 0
}

type ListUtxosRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Chain           Chain                  `protobuf:"varint,1,opt,name=chain,proto3,enum=xswallet.Chain" json:"chain,omitempty"`
	IncludeReserved bool                   `protobuf:"varint,2,opt,name=include_reserved,json=includeReserved,proto3" json:"include_reserved,omitempty"` // Inclui UTXOs reservados para swaps
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListUtxosRequest) Reset() {
	*x = ListUtxosRequest{}
	mi := &file_wallet_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUtxosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUtxosRequest) ProtoMessage() {}

func (x *ListUtxosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUtxosRequest.ProtoReflect.Descriptor instead.
func (*ListUtxosRequest) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{24}
}

func (x *ListUtxosRequest) GetChain() Chain {
	if x != nil {
		return x.Chain
	}
	return Chain_CHAIN_UNSPECIFIED
}

func (x *ListUtxosRequest) GetIncludeReserved() bool {
	if x != nil {
		return x.IncludeReserved
	}
	return false
}

type ListUtxosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Utxos         []*Utxo                `protobuf:"bytes,1,rep,name=utxos,proto3" json:"utxos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUtxosResponse) Reset() {
	*x = ListUtxosResponse{}
	mi := &file_wallet_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUtxosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUtxosResponse) ProtoMessage() {}

func (x *ListUtxosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUtxosResponse.ProtoReflect.Descriptor instead.
func (*ListUtxosResponse) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{25}
}

func (x *ListUtxosResponse) GetUtxos() []*Utxo {
	if x != nil {
		return x.Utxos
	}
	return nil
}

type Utxo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Txid              string                 `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
	Vout              uint32                 `protobuf:"varint,2,opt,name=vout,proto3" json:"vout,omitempty"`
	AmountSat         uint64                 `protobuf:"varint,3,opt,name=amount_sat,json=amountSat,proto3" json:"amount_sat,omitempty"`
	Address           string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Confirmations     int32                  `protobuf:"varint,5,opt,name=confirmations,proto3" json:"confirmations,omitempty"`
	Reserved          bool                   `protobuf:"varint,6,opt,name=reserved,proto3" json:"reserved,omitempty"` // Reservado para swap
	ReservedForSwapId string                 `protobuf:"bytes,7,opt,name=reserved_for_swap_id,json=reservedForSwapId,proto3" json:"reserved_for_swap_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Utxo) Reset() {
	*x = Utxo{}
	mi := &file_wallet_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Utxo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Utxo) ProtoMessage() {}

func (x *Utxo) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Utxo.ProtoReflect.Descriptor instead.
func (*Utxo) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{26}
}

func (x *Utxo) GetTxid() string {
	if x != nil {
		return x.Txid
	}
	return ""
}

func (x *Utxo) GetVout() uint32 {
	if x != nil {
		return x.Vout
	}
	return 0
}

func (x *Utxo) GetAmountSat() uint64 {
	if x != nil {
		return x.AmountSat
	}
	return 0
}

func (x *Utxo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Utxo) GetConfirmations() int32 {
	if x != nil {
		return x.Confirmations
	}
	return 0
}

func (x *Utxo) GetReserved() bool {
	if x != nil {
		return x.Reserved
	}
	return false
}

func (x *Utxo) GetReservedForSwapId() string {
	if x != nil {
		return x.ReservedForSwapId
	}
	return ""
}

type ListTransactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chain         Chain                  `protobuf:"varint,1,opt,name=chain,proto3,enum=xswallet.Chain" json:"chain,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionsRequest) Reset() {
	*x = ListTransactionsRequest{}
	mi := &file_wallet_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionsRequest) ProtoMessage() {}

func (x *ListTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionsRequest.ProtoReflect.Descriptor instead.
func (*ListTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{27}
}

func (x *ListTransactionsRequest) GetChain() Chain {
	if x != nil {
		return x.Chain
	}
	return Chain_CHAIN_UNSPECIFIED
}

func (x *ListTransactionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListTransactionsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListTransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionsResponse) Reset() {
	*x = ListTransactionsResponse{}
	mi := &file_wallet_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionsResponse) ProtoMessage() {}

func (x *ListTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionsResponse.ProtoReflect.Descriptor instead.
func (*ListTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{28}
}

func (x *ListTransactionsResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *ListTransactionsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Txid          string                 `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
	Chain         Chain                  `protobuf:"varint,2,opt,name=chain,proto3,enum=xswallet.Chain" json:"chain,omitempty"`
	AmountSat     int64                  `protobuf:"varint,3,opt,name=amount_sat,json=amountSat,proto3" json:"amount_sat,omitempty"` // Positivo = recebido, negativo = enviado
	FeeSat        uint64                 `protobuf:"varint,4,opt,name=fee_sat,json=feeSat,proto3" json:"fee_sat,omitempty"`
	Confirmations int32                  `protobuf:"varint,5,opt,name=confirmations,proto3" json:"confirmations,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Label         string                 `protobuf:"bytes,7,opt,name=label,proto3" json:"label,omitempty"`
	SwapId        string                 `protobuf:"bytes,8,opt,name=swap_id,json=swapId,proto3" json:"swap_id,omitempty"` // Se relacionado a swap
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_wallet_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{29}
}

func (x *Transaction) GetTxid() string {
	if x != nil {
		return x.Txid
	}
	return ""
}

func (x *Transaction) GetChain() Chain {
	if x != nil {
		return x.Chain
	}
	return Chain_CHAIN_UNSPECIFIED
}

func (x *Transaction) GetAmountSat() int64 {
	if x != nil {
		return x.AmountSat
	}
	return 0
}

func (x *Transaction) GetFeeSat() uint64 {
	if x != nil {
		return x.FeeSat
	}
	return 0
}

func (x *Transaction) GetConfirmations() int32 {
	if x != nil {
		return x.Confirmations
	}
	return 0
}

func (x *Transaction) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Transaction) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Transaction) GetSwapId() string {
	if x != nil {
		return x.SwapId
	}
	return ""
}

type SendOnchainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chain         Chain                  `protobuf:"varint,1,opt,name=chain,proto3,enum=xswallet.Chain" json:"chain,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	AmountSat     uint64                 `protobuf:"varint,3,opt,name=amount_sat,json=amountSat,proto3" json:"amount_sat,omitempty"`
	FeeRateSatVb  uint64                 `protobuf:"varint,4,opt,name=fee_rate_sat_vb,json=feeRateSatVb,proto3" json:"fee_rate_sat_vb,omitempty"` // Opcional (sat/vB)
	SubtractFee   bool                   `protobuf:"varint,5,opt,name=subtract_fee,json=subtractFee,proto3" json:"subtract_fee,omitempty"`        // Se true, desconta fee do amount
	Label         string                 `protobuf:"bytes,6,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendOnchainRequest) Reset() {
	*x = SendOnchainRequest{}
	mi := &file_wallet_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendOnchainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendOnchainRequest) ProtoMessage() {}

func (x *SendOnchainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendOnchainRequest.ProtoReflect.Descriptor instead.
func (*SendOnchainRequest) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{30}
}

func (x *SendOnchainRequest) GetChain() Chain {
	if x != nil {
		return x.Chain
	}
	return Chain_CHAIN_UNSPECIFIED
}

func (x *SendOnchainRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *SendOnchainRequest) GetAmountSat() uint64 {
	if x != nil {
		return x.AmountSat
	}
	return 0
}

func (x *SendOnchainRequest) GetFeeRateSatVb() uint64 {
	if x != nil {
		return x.FeeRateSatVb
	}
	return 0
}

func (x *SendOnchainRequest) GetSubtractFee() bool {
	if x != nil {
		return x.SubtractFee
	}
	return false
}

func (x *SendOnchainRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type SendOnchainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Txid          string                 `protobuf:"bytes,2,opt,name=txid,proto3" json:"txid,omitempty"`
	FeeSat        uint64                 `protobuf:"varint,3,opt,name=fee_sat,json=feeSat,proto3" json:"fee_sat,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendOnchainResponse) Reset() {
	*x = SendOnchainResponse{}
	mi := &file_wallet_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendOnchainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendOnchainResponse) ProtoMessage() {}

func (x *SendOnchainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendOnchainResponse.ProtoReflect.Descriptor instead.
func (*SendOnchainResponse) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{31}
}

func (x *SendOnchainResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendOnchainResponse) GetTxid() string {
	if x != nil {
		return x.Txid
	}
	return ""
}

func (x *SendOnchainResponse) GetFeeSat() uint64 {
	if x != nil {
		return x.FeeSat
	}
	return 0
}

func (x *SendOnchainResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_wallet_proto protoreflect.FileDescriptor

const file_wallet_proto_rawDesc = "" +
	"\n" +
	"\fwallet.proto\x12\bxswallet\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\fcommon.proto\"\xaa\x01\n" +
	"\x16InitializeVaultRequest\x127\n" +
	"\bgenerate\x18\x01 \x01(\v2\x19.xswallet.GenerateNewSeedH\x00R\bgenerate\x126\n" +
	"\x06import\x18\x02 \x01(\v2\x1c.xswallet.ImportExistingSeedH\x00R\x06import\x12\x10\n" +
	"\x03pin\x18\x03 \x01(\tR\x03pinB\r\n" +
	"\vseed_source\"0\n" +
	"\x0fGenerateNewSeed\x12\x1d\n" +
	"\n" +
	"word_count\x18\x01 \x01(\x05R\twordCount\"P\n" +
	"\x12ImportExistingSeed\x12\x1a\n" +
	"\bmnemonic\x18\x01 \x01(\tR\bmnemonic\x12\x1e\n" +
	"\n" +
	"passphrase\x18\x02 \x01(\tR\n" +
	"passphrase\"\x93\x01\n" +
	"\x17InitializeVaultResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1a\n" +
	"\bmnemonic\x18\x02 \x01(\tR\bmnemonic\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"&\n" +
	"\x12UnlockVaultRequest\x12\x10\n" +
	"\x03pin\x18\x01 \x01(\tR\x03pin\"\xa2\x01\n" +
	"\x13UnlockVaultResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12-\n" +
	"\x12attempts_remaining\x18\x04 \x01(\x05R\x11attemptsRemaining\"1\n" +
	"\x10LockVaultRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"-\n" +
	"\x11LockVaultResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x17\n" +
	"\x15GetVaultStatusRequest\"\xa1\x02\n" +
	"\vVaultStatus\x121\n" +
	"\x05state\x18\x01 \x01(\x0e2\x1b.xswallet.VaultStatus.StateR\x05state\x12'\n" +
	"\x0ffailed_attempts\x18\x02 \x01(\x05R\x0efailedAttempts\x12?\n" +
	"\rlockout_until\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\flockoutUntil\"u\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15STATE_NOT_INITIALIZED\x10\x01\x12\x10\n" +
	"\fSTATE_LOCKED\x10\x02\x12\x12\n" +
	"\x0eSTATE_UNLOCKED\x10\x03\x12\x14\n" +
	"\x10STATE_LOCKED_OUT\x10\x04\"\x18\n" +
	"\x16GetBackupStatusRequest\"\xa2\x02\n" +
	"\fBackupStatus\x12J\n" +
	"\"has_pending_swaps_requiring_backup\x18\x01 \x01(\bR\x1ehasPendingSwapsRequiringBackup\x12,\n" +
	"\x12pending_swap_count\x18\x02 \x01(\x05R\x10pendingSwapCount\x12@\n" +
	"\x0elast_backup_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\flastBackupAt\x12-\n" +
	"\x12backup_recommended\x18\x04 \x01(\bR\x11backupRecommended\x12'\n" +
	"\x0fwarning_message\x18\x05 \x01(\tR\x0ewarningMessage\"b\n" +
	"\x19MarkBackupCompleteRequest\x12E\n" +
	"\x10backup_timestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x0fbackupTimestamp\":\n" +
	"\x11GetBalanceRequest\x12%\n" +
	"\x05chain\x18\x01 \x01(\x0e2\x0f.xswallet.ChainR\x05chain\"\xcd\x01\n" +
	"\x0fBalanceResponse\x12%\n" +
	"\x05chain\x18\x01 \x01(\x0e2\x0f.xswallet.ChainR\x05chain\x12#\n" +
	"\rconfirmed_sat\x18\x02 \x01(\x04R\fconfirmedSat\x12'\n" +
	"\x0funconfirmed_sat\x18\x03 \x01(\x04R\x0eunconfirmedSat\x12(\n" +
	"\x10pending_swap_sat\x18\x04 \x01(\x04R\x0ependingSwapSat\x12\x1b\n" +
	"\ttotal_sat\x18\x05 \x01(\x04R\btotalSat\"\x17\n" +
	"\x15GetAllBalancesRequest\"\xa0\x01\n" +
	"\x13AllBalancesResponse\x12+\n" +
	"\x03btc\x18\x01 \x01(\v2\x19.xswallet.BalanceResponseR\x03btc\x121\n" +
	"\x06liquid\x18\x02 \x01(\v2\x19.xswallet.BalanceResponseR\x06liquid\x12)\n" +
	"\x02ln\x18\x03 \x01(\v2\x19.xswallet.BalanceResponseR\x02ln\"\x16\n" +
	"\x14WatchBalancesRequest\"\xbd\x01\n" +
	"\rBalanceUpdate\x12%\n" +
	"\x05chain\x18\x01 \x01(\x0e2\x0f.xswallet.ChainR\x05chain\x123\n" +
	"\abalance\x18\x02 \x01(\v2\x19.xswallet.BalanceResponseR\abalance\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"S\n" +
	"\x14GetNewAddressRequest\x12%\n" +
	"\x05chain\x18\x01 \x01(\x0e2\x0f.xswallet.ChainR\x05chain\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\"\x91\x01\n" +
	"\x0fAddressResponse\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12%\n" +
	"\x05chain\x18\x02 \x01(\x0e2\x0f.xswallet.ChainR\x05chain\x12'\n" +
	"\x0fderivation_path\x18\x03 \x01(\tR\x0ederivationPath\x12\x14\n" +
	"\x05label\x18\x04 \x01(\tR\x05label\"`\n" +
	"\x14ListAddressesRequest\x12%\n" +
	"\x05chain\x18\x01 \x01(\x0e2\x0f.xswallet.ChainR\x05chain\x12!\n" +
	"\finclude_used\x18\x02 \x01(\bR\vincludeUsed\"L\n" +
	"\x15ListAddressesResponse\x123\n" +
	"\taddresses\x18\x01 \x03(\v2\x15.xswallet.AddressInfoR\taddresses\"\xc2\x01\n" +
	"\vAddressInfo\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12%\n" +
	"\x05chain\x18\x02 \x01(\x0e2\x0f.xswallet.ChainR\x05chain\x12'\n" +
	"\x0fderivation_path\x18\x03 \x01(\tR\x0ederivationPath\x12\x14\n" +
	"\x05label\x18\x04 \x01(\tR\x05label\x12\x12\n" +
	"\x04used\x18\x05 \x01(\bR\x04used\x12\x1f\n" +
	"\vbalance_sat\x18\x06 \x01(\x04R\n" +
	"balanceSat\"d\n" +
	"\x10ListUtxosRequest\x12%\n" +
	"\x05chain\x18\x01 \x01(\x0e2\x0f.xswallet.ChainR\x05chain\x12)\n" +
	"\x10include_reserved\x18\x02 \x01(\bR\x0fincludeReserved\"9\n" +
	"\x11ListUtxosResponse\x12$\n" +
	"\x05utxos\x18\x01 \x03(\v2\x0e.xswallet.UtxoR\x05utxos\"\xda\x01\n" +
	"\x04Utxo\x12\x12\n" +
	"\x04txid\x18\x01 \x01(\tR\x04txid\x12\x12\n" +
	"\x04vout\x18\x02 \x01(\rR\x04vout\x12\x1d\n" +
	"\n" +
	"amount_sat\x18\x03 \x01(\x04R\tamountSat\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12$\n" +
	"\rconfirmations\x18\x05 \x01(\x05R\rconfirmations\x12\x1a\n" +
	"\breserved\x18\x06 \x01(\bR\breserved\x12/\n" +
	"\x14reserved_for_swap_id\x18\a \x01(\tR\x11reservedForSwapId\"n\n" +
	"\x17ListTransactionsRequest\x12%\n" +
	"\x05chain\x18\x01 \x01(\x0e2\x0f.xswallet.ChainR\x05chain\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"v\n" +
	"\x18ListTransactionsResponse\x129\n" +
	"\ftransactions\x18\x01 \x03(\v2\x15.xswallet.TransactionR\ftransactions\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\x8f\x02\n" +
	"\vTransaction\x12\x12\n" +
	"\x04txid\x18\x01 \x01(\tR\x04txid\x12%\n" +
	"\x05chain\x18\x02 \x01(\x0e2\x0f.xswallet.ChainR\x05chain\x12\x1d\n" +
	"\n" +
	"amount_sat\x18\x03 \x01(\x03R\tamountSat\x12\x17\n" +
	"\afee_sat\x18\x04 \x01(\x04R\x06feeSat\x12$\n" +
	"\rconfirmations\x18\x05 \x01(\x05R\rconfirmations\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x14\n" +
	"\x05label\x18\a \x01(\tR\x05label\x12\x17\n" +
	"\aswap_id\x18\b \x01(\tR\x06swapId\"\xd4\x01\n" +
	"\x12SendOnchainRequest\x12%\n" +
	"\x05chain\x18\x01 \x01(\x0e2\x0f.xswallet.ChainR\x05chain\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x1d\n" +
	"\n" +
	"amount_sat\x18\x03 \x01(\x04R\tamountSat\x12%\n" +
	"\x0ffee_rate_sat_vb\x18\x04 \x01(\x04R\ffeeRateSatVb\x12!\n" +
	"\fsubtract_fee\x18\x05 \x01(\bR\vsubtractFee\x12\x14\n" +
	"\x05label\x18\x06 \x01(\tR\x05label\"\x81\x01\n" +
	"\x13SendOnchainResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04txid\x18\x02 \x01(\tR\x04txid\x12\x17\n" +
	"\afee_sat\x18\x03 \x01(\x04R\x06feeSat\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage2\xd2\b\n" +
	"\rWalletService\x12V\n" +
	"\x0fInitializeVault\x12 .xswallet.InitializeVaultRequest\x1a!.xswallet.InitializeVaultResponse\x12J\n" +
	"\vUnlockVault\x12\x1c.xswallet.UnlockVaultRequest\x1a\x1d.xswallet.UnlockVaultResponse\x12D\n" +
	"\tLockVault\x12\x1a.xswallet.LockVaultRequest\x1a\x1b.xswallet.LockVaultResponse\x12H\n" +
	"\x0eGetVaultStatus\x12\x1f.xswallet.GetVaultStatusRequest\x1a\x15.xswallet.VaultStatus\x12K\n" +
	"\x0fGetBackupStatus\x12 .xswallet.GetBackupStatusRequest\x1a\x16.xswallet.BackupStatus\x12Q\n" +
	"\x12MarkBackupComplete\x12#.xswallet.MarkBackupCompleteRequest\x1a\x16.xswallet.BackupStatus\x12D\n" +
	"\n" +
	"GetBalance\x12\x1b.xswallet.GetBalanceRequest\x1a\x19.xswallet.BalanceResponse\x12P\n" +
	"\x0eGetAllBalances\x12\x1f.xswallet.GetAllBalancesRequest\x1a\x1d.xswallet.AllBalancesResponse\x12J\n" +
	"\rGetNewAddress\x12\x1e.xswallet.GetNewAddressRequest\x1a\x19.xswallet.AddressResponse\x12P\n" +
	"\rListAddresses\x12\x1e.xswallet.ListAddressesRequest\x1a\x1f.xswallet.ListAddressesResponse\x12D\n" +
	"\tListUtxos\x12\x1a.xswallet.ListUtxosRequest\x1a\x1b.xswallet.ListUtxosResponse\x12Y\n" +
	"\x10ListTransactions\x12!.xswallet.ListTransactionsRequest\x1a\".xswallet.ListTransactionsResponse\x12J\n" +
	"\vSendOnchain\x12\x1c.xswallet.SendOnchainRequest\x1a\x1d.xswallet.SendOnchainResponse\x12J\n" +
	"\rWatchBalances\x12\x1e.xswallet.WatchBalancesRequest\x1a\x17.xswallet.BalanceUpdate0\x01B#Z!github.com/xs-wallet/xscore/protob\x06proto3"

var (
	file_wallet_proto_rawDescOnce sync.Once
	file_wallet_proto_rawDescData []byte
)

func file_wallet_proto_rawDescGZIP() []byte {
	file_wallet_proto_rawDescOnce.Do(func() {
		file_wallet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wallet_proto_rawDesc), len(file_wallet_proto_rawDesc)))
	})
	return file_wallet_proto_rawDescData
}

var file_wallet_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_wallet_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_wallet_proto_goTypes = []any{
	(VaultStatus_State)(0),            // 0: xswallet.VaultStatus.State
	(*InitializeVaultRequest)(nil),    // 1: xswallet.InitializeVaultRequest
	(*GenerateNewSeed)(nil),           // 2: xswallet.GenerateNewSeed
	(*ImportExistingSeed)(nil),        // 3: xswallet.ImportExistingSeed
	(*InitializeVaultResponse)(nil),   // 4: xswallet.InitializeVaultResponse
	(*UnlockVaultRequest)(nil),        // 5: xswallet.UnlockVaultRequest
	(*UnlockVaultResponse)(nil),       // 6: xswallet.UnlockVaultResponse
	(*LockVaultRequest)(nil),          // 7: xswallet.LockVaultRequest
	(*LockVaultResponse)(nil),         // 8: xswallet.LockVaultResponse
	(*GetVaultStatusRequest)(nil),     // 9: xswallet.GetVaultStatusRequest
	(*VaultStatus)(nil),               // 10: xswallet.VaultStatus
	(*GetBackupStatusRequest)(nil),    // 11: xswallet.GetBackupStatusRequest
	(*BackupStatus)(nil),              // 12: xswallet.BackupStatus
	(*MarkBackupCompleteRequest)(nil), // 13: xswallet.MarkBackupCompleteRequest
	(*GetBalanceRequest)(nil),         // 14: xswallet.GetBalanceRequest
	(*BalanceResponse)(nil),           // 15: xswallet.BalanceResponse
	(*GetAllBalancesRequest)(nil),     // 16: xswallet.GetAllBalancesRequest
	(*AllBalancesResponse)(nil),       // 17: xswallet.AllBalancesResponse
	(*WatchBalancesRequest)(nil),      // 18: xswallet.WatchBalancesRequest
	(*BalanceUpdate)(nil),             // 19: xswallet.BalanceUpdate
	(*GetNewAddressRequest)(nil),      // 20: xswallet.GetNewAddressRequest
	(*AddressResponse)(nil),           // 21: xswallet.AddressResponse
	(*ListAddressesRequest)(nil),      // 22: xswallet.ListAddressesRequest
	(*ListAddressesResponse)(nil),     // 23: xswallet.ListAddressesResponse
	(*AddressInfo)(nil),               // 24: xswallet.AddressInfo
	(*ListUtxosRequest)(nil),          // 25: xswallet.ListUtxosRequest
	(*ListUtxosResponse)(nil),         // 26: xswallet.ListUtxosResponse
	(*Utxo)(nil),                      // 27: xswallet.Utxo
	(*ListTransactionsRequest)(nil),   // 28: xswallet.ListTransactionsRequest
	(*ListTransactionsResponse)(nil),  // 29: xswallet.ListTransactionsResponse
	(*Transaction)(nil),               // 30: xswallet.Transaction
	(*SendOnchainRequest)(nil),        // 31: xswallet.SendOnchainRequest
	(*SendOnchainResponse)(nil),       // 32: xswallet.SendOnchainResponse
	(*timestamppb.Timestamp)(nil),     // 33: google.protobuf.Timestamp
	(Chain)(0),                        // 34: xswallet.Chain
}
var file_wallet_proto_depIdxs = []int32{
	2,  // 0: xswallet.InitializeVaultRequest.generate:type_name -> xswallet.GenerateNewSeed
	3,  // 1: xswallet.InitializeVaultRequest.import:type_name -> xswallet.ImportExistingSeed
	0,  // 2: xswallet.VaultStatus.state:type_name -> xswallet.VaultStatus.State
	33, // 3: xswallet.VaultStatus.lockout_until:type_name -> google.protobuf.Timestamp
	33, // 4: xswallet.BackupStatus.last_backup_at:type_name -> google.protobuf.Timestamp
	33, // 5: xswallet.MarkBackupCompleteRequest.backup_timestamp:type_name -> google.protobuf.Timestamp
	34, // 6: xswallet.GetBalanceRequest.chain:type_name -> xswallet.Chain
	34, // 7: xswallet.BalanceResponse.chain:type_name -> xswallet.Chain
	15, // 8: xswallet.AllBalancesResponse.btc:type_name -> xswallet.BalanceResponse
	15, // 9: xswallet.AllBalancesResponse.liquid:type_name -> xswallet.BalanceResponse
	15, // 10: xswallet.AllBalancesResponse.ln:type_name -> xswallet.BalanceResponse
	34, // 11: xswallet.BalanceUpdate.chain:type_name -> xswallet.Chain
	15, // 12: xswallet.BalanceUpdate.balance:type_name -> xswallet.BalanceResponse
	33, // 13: xswallet.BalanceUpdate.timestamp:type_name -> google.protobuf.Timestamp
	34, // 14: xswallet.GetNewAddressRequest.chain:type_name -> xswallet.Chain
	34, // 15: xswallet.AddressResponse.chain:type_name -> xswallet.Chain
	34, // 16: xswallet.ListAddressesRequest.chain:type_name -> xswallet.Chain
	24, // 17: xswallet.ListAddressesResponse.addresses:type_name -> xswallet.AddressInfo
	34, // 18: xswallet.AddressInfo.chain:type_name -> xswallet.Chain
	34, // 19: xswallet.ListUtxosRequest.chain:type_name -> xswallet.Chain
	27, // 20: xswallet.ListUtxosResponse.utxos:type_name -> xswallet.Utxo
	34, // 21: xswallet.ListTransactionsRequest.chain:type_name -> xswallet.Chain
	30, // 22: xswallet.ListTransactionsResponse.transactions:type_name -> xswallet.Transaction
	34, // 23: xswallet.Transaction.chain:type_name -> xswallet.Chain
	33, // 24: xswallet.Transaction.timestamp:type_name -> google.protobuf.Timestamp
	34, // 25: xswallet.SendOnchainRequest.chain:type_name -> xswallet.Chain
	1,  // 26: xswallet.WalletService.InitializeVault:input_type -> xswallet.InitializeVaultRequest
	5,  // 27: xswallet.WalletService.UnlockVault:input_type -> xswallet.UnlockVaultRequest
	7,  // 28: xswallet.WalletService.LockVault:input_type -> xswallet.LockVaultRequest
	9,  // 29: xswallet.WalletService.GetVaultStatus:input_type -> xswallet.GetVaultStatusRequest
	11, // 30: xswallet.WalletService.GetBackupStatus:input_type -> xswallet.GetBackupStatusRequest
	13, // 31: xswallet.WalletService.MarkBackupComplete:input_type -> xswallet.MarkBackupCompleteRequest
	14, // 32: xswallet.WalletService.GetBalance:input_type -> xswallet.GetBalanceRequest
	16, // 33: xswallet.WalletService.GetAllBalances:input_type -> xswallet.GetAllBalancesRequest
	20, // 34: xswallet.WalletService.GetNewAddress:input_type -> xswallet.GetNewAddressRequest
	22, // 35: xswallet.WalletService.ListAddresses:input_type -> xswallet.ListAddressesRequest
	25, // 36: xswallet.WalletService.ListUtxos:input_type -> xswallet.ListUtxosRequest
	28, // 37: xswallet.WalletService.ListTransactions:input_type -> xswallet.ListTransactionsRequest
	31, // 38: xswallet.WalletService.SendOnchain:input_type -> xswallet.SendOnchainRequest
	18, // 39: xswallet.WalletService.WatchBalances:input_type -> xswallet.WatchBalancesRequest
	4,  // 40: xswallet.WalletService.InitializeVault:output_type -> xswallet.InitializeVaultResponse
	6,  // 41: xswallet.WalletService.UnlockVault:output_type -> xswallet.UnlockVaultResponse
	8,  // 42: xswallet.WalletService.LockVault:output_type -> xswallet.LockVaultResponse
	10, // 43: xswallet.WalletService.GetVaultStatus:output_type -> xswallet.VaultStatus
	12, // 44: xswallet.WalletService.GetBackupStatus:output_type -> xswallet.BackupStatus
	12, // 45: xswallet.WalletService.MarkBackupComplete:output_type -> xswallet.BackupStatus
	15, // 46: xswallet.WalletService.GetBalance:output_type -> xswallet.BalanceResponse
	17, // 47: xswallet.WalletService.GetAllBalances:output_type -> xswallet.AllBalancesResponse
	21, // 48: xswallet.WalletService.GetNewAddress:output_type -> xswallet.AddressResponse
	23, // 49: xswallet.WalletService.ListAddresses:output_type -> xswallet.ListAddressesResponse
	26, // 50: xswallet.WalletService.ListUtxos:output_type -> xswallet.ListUtxosResponse
	29, // 51: xswallet.WalletService.ListTransactions:output_type -> xswallet.ListTransactionsResponse
	32, // 52: xswallet.WalletService.SendOnchain:output_type -> xswallet.SendOnchainResponse
	19, // 53: xswallet.WalletService.WatchBalances:output_type -> xswallet.BalanceUpdate
	40, // [40:54] is the sub-list for method output_type
	26, // [26:40] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_wallet_proto_init() }
func file_wallet_proto_init() {
	if File_wallet_proto != nil {
		return
	}
	file_common_proto_init()
	file_wallet_proto_msgTypes[0].OneofWrappers = []any{
		(*InitializeVaultRequest_Generate)(nil),
		(*InitializeVaultRequest_Import)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wallet_proto_rawDesc), len(file_wallet_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wallet_proto_goTypes,
		DependencyIndexes: file_wallet_proto_depIdxs,
		EnumInfos:         file_wallet_proto_enumTypes,
		MessageInfos:      file_wallet_proto_msgTypes,
	}.Build()
	File_wallet_proto = out.File
	file_wallet_proto_goTypes = nil
	file_wallet_proto_depIdxs = nil
}
